### ISSUE TITLE
Are threads supported?

### ISSUE THREAD

**Issue by brachna** [kayhayen/Nuitka#106]
Nuitka 0.5.32.7, Python 3.6.5 64bit, Windows 8.1 64bit.
Used pip for installation.

Not a bug report, just wanted clarification.
The site mentions that threads are not supported (http://nuitka.net/pages/differences.html).
Threads are crucial for my program, so I did a test before deciding to switch to CPython.
It looks like threads are working? What's the current state of threading support in Nuitka?

**Comment by kayhayen** [comment]
Yes they are. That content is very old and I think not linked by the rest of the site anymore, but still there, or how did you get there?

Eventually thread support was added.

I need to remove that page, so it gets not rendered/deployed anymore. Expect the link from above to go 404 at some time.

Yours,
Kay

**Comment by brachna** [comment]
I got that page while using Google search.
Glad to know threading is supported. Thank you for this wonderful project.

**Comment by ArniDagur** [comment]
@kayhayen It seems that the site is still up, but I'm glad that threading is now supported!

**Comment by kskuhlman** [comment]
fwiw, Google led me there as well.  Please consider a redirect instead of 404.

**Comment by kayhayen** [comment]
It's gone now, sorry for the delay. I am not deploying the site with deleting files, I need to change that, so all these old pages go away.

A redirect is probably not worth it, Google will notice 404 soon, and stop suggesting it.

Yours,
Kay
