### ISSUE TITLE
Proper way to test nuitka standalone executables

### ISSUE THREAD

**Issue by brupelo** [kayhayen/Nuitka#109]
Here's some additional suggestions to people that would like to report bugs and also test nuitka the RIGHT way :)

 - Use virtual machines that allow you to test the nuitka outcome on a clean box
 - In case you're not willing to use virtual machines, make sure you test the nuitka outcome on a clean operating system. Clean in this context means a fresh installed OS with the system updates (optional)
 - Standalone executable produced by nuitka should run on a guest operating system with/without updates

Why? Well, following these simple advices will allow us to discover hidden bugs that in other cases wouldn't be revealed on a dev box. For instance, simple example, this [assumption](https://github.com/kayhayen/Nuitka/blob/develop/nuitka/freezer/Standalone.py#L791) here... that's really bad as the Visual Studio runtime redistributable package are not installed by default on Windows and while it's very common that many software out there install these runtime libs and make it visible on PATH you shouldn't assume that and call the nuitka outcome Standalone. Standalone in my book is a software that should run out of the box (fresh OS) without 3rd party packages.

I've created a little utility that allows me to list all dlls available on PATH, I'll run them of some Windows guests (XP, Win7) very soon and post the results here.

**Comment by kayhayen** [comment]
Looking forward to the result @brupelo and this totally feels like it should be part of the User Manual in some form or the other.

**Comment by brupelo** [comment]
@kayhayen Found it, [how hard would be this to implement on nuitka Kay](https://stackoverflow.com/a/11305659/3809375)? 

Ie: Maybe adding a flag so the user can select the platform toolset and this will be added to the SCons project? Doesn't look very time consuming to implement...
