### ISSUE TITLE
How to build windows xp apps using nuitka?

### ISSUE THREAD

**Issue by brupelo** [kayhayen/Nuitka#110]
Has anyone managed to build a windows xp application using nuitka? If it's so, could you advice about the toolchain used as well as the flags?

Thanks.

**Comment by brupelo** [comment]
Building an xp app using the [IDE is straightforward](https://stackoverflow.com/a/35666906/3809375).

Unfortunately after a lot of googling I haven't been able yet to instruct SCons to use the proper platform toolset (ie: Windows XP (v140_xp)). 

Hopefully someone else who's proficient with SCons can advice here, so far I've got this documents:

 - There is this flag ... https://scons.org/doc/HTML/scons-man.html#cv-MSSDK_VERSION but not sure if that's what we want here... as I guess `v140_xp` platform toolset not only just setup the include/lib paths to point out to the old win7.0 sdk but presumably does something else in order to get windows xp compatible machine code :/

**Comment by kayhayen** [comment]
Why not use MinGW64 or same issue?

**Comment by brupelo** [comment]
Opened a [thread](https://stackoverflow.com/questions/52152135/how-to-build-windows-xp-application-with-vs2015-and-scons) asking about it on StackOverflow... let's see if that speed up things as I see these github issues don't have too much traffic :D

**Comment by brupelo** [comment]
@kayhayen Sure, whatever it works is fine with me, last time i've used mingw64 was, 10 years ago? Assuming I've installed already that compiler, is this [http://mingw.org/](http://mingw.org/) the official site? Which flags should i use with nuitka?

**Comment by kayhayen** [comment]
@brupelo no that is MinGW which is not as Windows compatible as its fork MinGW64. Check out User Manual, aka README.rst, I think I called even what variant to choose in the last release or upcoming, I forgot.

I think I recall something about a define needed to enable WinXP somehow.

```
# The 32 bits MinGW does not default for API level properly, so help it.
if mingw_mode:
    # Windows XP
    env.Append(
        CPPDEFINES = ["_WIN32_WINNT=0x0501"]
    )

```

As for flags, normally none are needed, or that is at least the intent. As for getting old MS platform kits to work might be a tough call, if Scons doesn't alread do it.

For MinGW64, specifiy as CC the full path to gcc.exe  or use --mingw64 and have it installed in the suggested spots, where it is automatically found. Unlike what its name suggeste, there is a 32 bits variant.

I will check out your stuff once I return from holiday next week. No access to Windows here at all.

Yours,
Kay

**Comment by brupelo** [comment]
@kayhayen Ok, i've made a couple of tests to try to build a hello world program (ie: `print("hello world")`) using that mingw-64 thing and the compilation will produce a lot of errors, here's what i tried:

 1) Download [http://win-builds.org/1.5.0/win-builds-1.5.0.exe](http://win-builds.org/1.5.0/win-builds-1.5.0.exe)
 2) Install mingw64 on d:\software\mingw_x86 (x86)
 3) Open a command prompt and do `set PATH=d:\software\mingw_x86\bin;%PATH%` or `set PATH=D:\software\mingw_x86\i686-w64-mingw32\bin;%PATH%`
 - Run `nuitka3 a.py --standalone --mingw --output-dir=build --recurse-all`

The result is a lot of warnings and errors so I'm clearly doing something wrong here... Anyway, I'll stop trying and adding more content to these github issues till you come back.

Enjoy your holidays \o

Yours,
B.

**Comment by brupelo** [comment]
@kayhayen You're absolutely right, I was using a very old version of gcc (~4.x), I've installed the latest available version (8.1.0) and nuitka project will be packaged ok. In any case, the final standalone outcome won't be able to run properly on xp because shipped dlls are not good ones.

Really tricky problem this one, I was excited to be able to run some of my python apps on the good old xp but i don't see any happy ending to solve this issue properly... If someday you want to give it a shot to this issue you'll soon realize some dll functions used by the nuitka project (ie: ones living in kernel32.dll)  won't exist on the system dlls living on xp... And it won't matter if you copy the windows7 dlls into xp, you'll face other sort of issues... Guess this is just bad luck for me and all Chinese people that still using the good old unsupported by ms wonderful windows XP :)

**Comment by kayhayen** [comment]
@brupelo Can you be specific, which ones that are, kernel32.dll calls? 

git grep -i kernel32 gives only few hits, some of which are scons, some appdirs, and some are for finding the DLL. Or do you mean at run time? It also ought to do nothing too dramatic. Or maybe you are confusing this with MinGW64 run time having stopped to support WinXP which is a possibility too.

Looking forward to what calls these are.

Yours,
Kay

**Comment by kayhayen** [comment]
@brupelo BTW: Do not copy DLLs from any other system, that cannot be it, and is unlikely to work anyway. Windows XP compiled binaries are supposed to work up to Windows 10, so it must be be needed. Doing that, you are likely only going to confuse yourself.

**Comment by brupelo** [comment]
@kayhayen Kay, I've found this really interesting [article](https://ntcore.com/?p=458) which is related to the main problem here, the article is pure gold and it saves a lot of time. My research was leading me exactly to what's explained exactly on that article. Not sure how interested you're on these type of subjects but if you do I strongly recommend you to take a look as it clarifies quite well the whole matter about these existing api-ms* dlls. Plus, after reading the article what the platform toolset switch makes more sense, as I believe it just modifies some fields of the PE headers so windows xp loader can deal with them.

Talking about visual studio redistributable libraries... You can see the installers are shipped with visual studio itself (you can find them at `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\1033`). And it's worth noting these redistributable packages are installed in some of the windows updates. More info about it [here](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000P7hcSAC). Adding these notes as I'd also talked about environment isolation very briefly on the other github issue but without giving too much details about what's and what's not shipped by vanilla windows.

Anyway, don't have too much time to play around with this one but eventually I'll find it and I'll make it work as it really interests me.

PS: Just for the record, my environment over here is:

  a) Windows7 as devbox (python3.6+vs2015+mingw-64) ---> I deploy standalone packages with nuitka
  b) Windowsxp/Window7/Centos6/7/Ubuntus as virtualbox guests ----> The idea is the nuitka packages generated by a) will be tested/consumed by the windows guests here

**Comment by brupelo** [comment]
Here's a little comparison about how visual studio's platform toolset flag affect to the PE headers (you can see the platform toolset i've compared on the window's titles suffix):

![comparison1](https://dl.dropboxusercontent.com/s/x7pd7mj9ap9ztbz/CFF%20Explorer_2018-09-05_13-57-01.png)

Interesting stuff.

**Comment by brupelo** [comment]
@kayhayen Found [this](https://stackoverflow.com/questions/11544563/can-i-set-the-platform-toolset-from-the-command-line-when-building-with-vs2010s), you're the expert using SCons, any idea whether we could use that information somehow to specify the platform toolset to SCons?

**Comment by kayhayen** [comment]
@brupelo There is still your comment on why to use Scons in the first place. I want to make it a question issue later, as this comes up frequently.

When Nuitka was started, or even first presented to the public, KDE was still using "waf", "ninja build" was not yet an option. I really felt that Scons is a simple to use solution for the task at hand, that is to build an extension module for CPython or a binary that embeds Python.

Flexibility in project generation, etc. never were a point. The name "SingleExe.scons" derived from the idea, that this was only the first of many projects to exist, but that didn't happen, it works.

Scons dealt with how to call cl.exe, g++.exe, and all the details of what compilers to call very nicely, even offering out of the box features like finding MSVC from Windows registry, while still allowing to use a free compiler. With the many variants, editions, of MSVC, that is tedious work. Later I and others were able to add new ones easily.

Basically it's also easy to use. Adding a compiler flag is as simple as this:

```
        # Disable warnings, that CPython headers already show.
        if python_version >= "3.4":
            env.Append(
                CCFLAGS = [
                    "/wd4512", "/wd4510", "/wd4610"
                ]
            )

```

Adding a C define value is this:

```
# MinGW for 64 bits needs this due to CPython bugs.
if win_target and target_arch == "x86_64" and gcc_mode:
    env.Append(
        CPPDEFINES = ["MS_WIN64"]
    )

```

Adding a linker flag, is this easy:

```
    env.Append(
        LINKFLAGS = ["-Wl,-R,'%s'" % rpath]
    )

```

Then changing the shared library suffix, is also easy:

`    env["SHLIBSUFFIX"] = getSharedLibrarySuffix()
`

That is something that needs to be done for Python, as it has its own ideas for how the thing should be named, and with some tools hacking that requires to get more manual.

The bad side of scons is big too. I fixed some bugs for concurrency myself. Creating and using Windows resource files is all manual code. Then Windows command lines are used in naive ways. For large link commands, they don*t work. Quoting is broken there too. And it's necessary to apply this rather rude hack too, to filter out known good warnings, errors, to filter them from unexpected ones.

Also, since no dlcache integration has happened, scons has its own caching that can be used for re-building faster, which is a good replacement for ccache on non-Windows.

Also handling unicode paths on Windows seems to be not Scons strongest trait. I have worked around that largely by making sure to use relative paths, so Scons never seens them.

To get back to your question there, why not use anything else? I am all in favor of replacing Scons, esp. with something better. But somebody else will have to do that work. I would hope for a faster startup time, where scons is really bad, discovering too many things it never will use, although I hacked that some, so e.g. it will not scan for the "D" compiler, or Fortan, etc. by removing those parts of Scons from the inline copies, or by monkey patching "Environment.Detect" with a wrapper that gives up very fast on blacklisted stuff.

For as long as Nuitka lives, Scons is hated by everybody. People recommend replacements. But the truth is, it does the job. And other tools will need work, and it*s not sure that they are all that more Windows compatible, or hackable for special needs.

As for your question, ultimately that setting must mean that the MSVC tools are called with options related to that. Nuitka is not using "msbuild" or "nmake" on Windows for obvious reasons. So if you can tell which option to use, adding them in SingleExe.scons will be trivial. But I think the article didn't say that. But surely there is an option to output the cl.exe and link.exe calls as they happen?

**Comment by brupelo** [comment]
@kayhayen Kay, thank you very much for such a detailed explanation, it makes total sense. First of all, let me clarify than my previous question wasn't intended to criticize the SCons choice as this wouldn't make much sense. For instance, it's very easy when you're reviewing a software which has been developed a long time ago and from a advantage position claiming things like "This should be done better, a better and newer fancy tech should had been used, why hasn't he used this or that ....".

I've been there, when I recall when I was younger to be "lucky" enough to work with huge legacy working systems with more than 30 years on production, millions of lines of code being used by major electrical companies and I used to think "tsk, the UI should be replaced with more modern tech, these submodules shouldn't have so many hacks covering so many specific use-cases, this should have been done better, that sucks, bla, bla, bla...". The truth is, it was a battle-tested software and when reviewing a software that's old enough you need to put yourself in the right perspective so you can understand the context of why decisions have been made like that in the very first place. Plus, something that you can see like a "hack" probably it's been the result of people researching/debugging that stuff for few hours... That is time/knowledge that has been put into the software that shouldn't be discarded thrown away easily, definitely that wouldn't be smart, would it? :)

The fact you've been able to cover such a big spectrum in terms of compilers/operating_systems/python_versions with nuitka since the very beginning is definitely a titanic task, really awesome and it's definitely something that much people would be willing to do (you've acomplished the job that should have been done by a whole team), hats off. 

Let me put it in other way, if I think how I'd face a project like Nuitka from scratch I'd probably pick up an easier/lazier different route than the one you chose. I'd probably create the project to fit just my needs in the first place but always trying to design the software to be extensible, for instance:

Let's say my favourite toolchain is {python3.6, windows, c++/vs2015}. I'd probably stick to that little subset and would make the compiler bug free just for that little subset but always having in mind the submodules should be easy to replace/extend by other people (delegating job is a really good thing). You know what I mean? Designing software in the way you can "hire"/rely on people to extend it is always nice. Of course, with that kind of approach the software would probably evolve in a slower pace and the job wouldn't get "done" as faster as the one that intends to cover the whole spectrum from the very beginning, does it make sense?

My point is, nuitka, as it is right now covers a lot use-cases and already try to give support to a lot of platforms/tools and that's definitely awesome, hats off about that... I'm a strong believer that software should be designed to be used as widely as possible by people and this is a point I really love about nuitka... On the other hand, something I don't like that much the more I get involved/read the code is the fact than replacing submodules isn't always very straightforward, for instance, let me make a very fast review here:

 - The freezer (depends, ...), this submodule has a very well-defined purpose and it should be easy to replace it by something else... or even better, should be possible not using a freezer at all. This should be a "movable" part of the whole system.
 - The builder (scons), same here, the important goal shouldn't be get rid of SCons but instead make the proper changes so this subsystem can be replaced by other alternatives easily. For instance, when I've got more spare time I'd definitely like to give it a shot to CMake as I've got quite a bit experience with it and I've already used it on some projects that build metacompilers with cmake as one of the "backends"
 - Decoupling options! I've talked about this one quite a lot on other issue but believe me, if we were able to decouple Options across the whole project a lot of new possibilites would be opened here and the whole project would increase in terms of quality/testability.

I guess in summary I could say that at this point Nuitka is an awesome project already (told that zillion times), period. But I believe making it more "friendly"/"extensible" so you can rely on other's people 
 help more easily would be a major improvement. When I say "rely" on other peoples help I don't mean replacing directly working parts but instead allowing these parts to be replaced in easily.... Making the software more pluggable, you know what I mean? I'm a big fan myself of plugin architecture based software and I tend to code my software upon abstractions rather than concretions all the time... As said before, this is usually a slower way to create software but when time goes it proves almost always to be a really good choice in the long term ;D

Anyway Kay, thank you very much for such a detailed explanation of yours, now I've got more context about the earlier decissions, that is great. I love those kind of elaborated explanations, this type of people's explanations not only helps to judge the existing product with the right perspective but also teaches valuable lessons that can be applied on other different situations.

> For as long as Nuitka lives, Scons is hated by everybody. People recommend replacements. But the truth is, it does the job. And other tools will need work, and it*s not sure that they are all that more Windows compatible, or hackable for special needs.

THESE are wise words! I usually tend to not fall in the trap of software hating that many people falls in... This is a better OS than that one, this language is better than this other one, this software/methodology is superior that this other... Those type of debates usually are nonsense :) . Plus, I'd say one of the more important factors when picking up tech is how old and how many people have contributed to the software itself... as that's a metric that tells quite a lot about "how much knowledge" people has "injected" into the software, if that makes sense hehe ;D

Anyway, let's come back to the topic then, WindowsXP compatible exes... I've given some bounties to the opened thread on SO so let's see if something else will give some answers about it, if not, I guess we'll need to achieve the task in a more manual way (ie: picking up the right cl & link flags to produce compatible exes).

Again, thanks for your previous answer, really appreciated.

PS. I don't want to sound like a smarty guy that knows everything so please correct me if I've said something clearly wrong or something you think of very differently as I love learning from talented experienced coders all the time ;)

**Comment by brupelo** [comment]
> But surely there is an option to output the cl.exe and link.exe calls as they happen?

Mmm, good question! i had missed this on my previous reply... I'll try to figure it out today increasing the verbose level by using the IDE directly and check how it affects to cl & link

**Comment by brupelo** [comment]
@kayhayen Good news, I've compared exhaustively the cl & link flags used when switching the platform toolset and here's my findings:

    v120_xp
    -------
    link: /SUBSYSTEM:CONSOLE",5.01"
    cl: /D "_USING_V110_SDK71_"

    v120
    ----
    link: /SUBSYSTEM:CONSOLE
    cl:

    v140_xp
    --------
    link: /SUBSYSTEM:CONSOLE",5.01"
    cl: /D "_USING_V110_SDK71_" /Zc:inline

    v140
    -------
    link: /SUBSYSTEM:CONSOLE
    cl: /Zc:inline

It's the first time I see you can add that extra string (5.01) to the /SUBSYSTEM flag , makes sense,
I guess this helps to the linker to change the startup code of the asm code and also the pe headers. So, let's make a little assumption here, let's say this set of flags is good enough to distinguish between xp and win7/8/8.1/10 ... How do we to test this on nuitka?

Btw, worth reading the whole docs about [/SUBSYSTEM](https://msdn.microsoft.com/en-us/library/fcc1zstk.aspx)

**Comment by kayhayen** [comment]
Well done @brupelo looks good.

There is this code in SingleExe.scons that allows you to pass any options you want to from the outside:

```
if "CCFLAGS" in os.environ:
    env.Append(CCFLAGS = os.environ["CCFLAGS"].split())
if "LDFLAGS" in os.environ:
    env.Append(LINKFLAGS = os.environ["LDFLAGS"].split())

```

So setting the proper environment variable values, you ought to be good. Try and use /D"define_name" so you do not have a space. I checked the subsystem docs, and noticed that there is stuff for subsystem already with MinGW64:

            env.Append(
                LINKFLAGS = ["-Wl,--subsystem,windows"]
            )

That is to disable the console, which for MSVC is done by providing "WinMain" entry point, as can be seen in MainProgram.c, not tinkering with subsystem at all yet. These two could be done via subsystem too, and if we specify this. 

So @brupelo if you come up with a set of options that makes "XP" work, one that makes "Windows 7" work, I suggest we have a Windows specific option added with these named targets, passing it along, much like the others, so we hide the ugly details of that in the "SingleExe.scons" as opposed to making the user pass it.

**Comment by brupelo** [comment]
@kayhayen Kay, awesome, sounds like a good plan to me, makes sense.

I'm pretty much sure it won't be as easy as just using plug in the right set of cl/link options and have the final exe working in xp out of the box... Well, maybe if you just used some old python versions such as 3.4/3.5 the thing would work out the box with these cl/link flags (i think 3.4/3.5 were the latest python versions to support xp out of the box?). 

In any case, my goal here will be able to create a nuitka packaged exe shipping **python>=3.6**, many of the software I wanted to package on xp is using 3.6 specific features extensively. That's also the main reason why I've pasted this amazing [article](https://ntcore.com/?p=458) in previous posts, as I'm sure I'll need to hack around eventually to make it work :)

Anyway, I'm not stuck anymore and right now there is a lot of job&testing to do here :) , I'll keep you posted. Really interesting stuff this one btw, learned a lot of things thanks to this whole research. Some people would think these type of projects trying to support outdated systems may be a waste of time but I strongly believe they're not, eventually the knowledge you adquire used to pay off when you want to implement other cool features to software.

Coding back \o

**Comment by kayhayen** [comment]
Well, trying the impossible won't work. Obviously XP could be supported for older Python versions, but I guess we are then not going to do it until somebody else finds interest in this. That person obviously is not going to be me though.

**Comment by polkovnikov** [comment]
BTW, I've created a good XP-runnable application using such .cmd script (using 32-bit python 2.7 with nuitka installed):
`
@set CXXFLAGS=/D_USING_V110_SDK71_
@set LDFLAGS=/SUBSYSTEM:CONSOLE,5.01
@call D:\bin2\Python27_x32\Scripts\nuitka.bat --standalone --recurse-all main.py
`

**Comment by kayhayen** [comment]
A couple of my customers are doing Python 3.4 and Windows XP. I consider it supported in Nuitka Commercial, but don't expect instructions that are better than this here, you basically need to install toolchain, Python and Nuitka and it should work, provided the software runs on Windows XP.
