### ISSUE TITLE
Standalone: Missing hidden dependency of uvloop

### ISSUE THREAD

**Issue by pbartyik** [kayhayen/Nuitka#115]
Platform: Ubuntu 18.04 4.15.0-33-generic
Running python within venv, Nuitka installed via pip3

> ./venv/bin/python3 -m nuitka --version
> 0.5.32.7
> 3.6.5 (default, Apr  1 2018, 05:46:30) 
> [GCC 7.3.0]
> /home/user/stuff/venv/bin/python3

Fresh venv created by:

> virtualenv -p /usr/bin/python3.6 venv

Nuitka installed as: 

> cd venv/bin && ./pip3 -q install nuitka

Nuitka ran as:

> PYTONPATH=/home/user/stuff/venv/lib/python3.6/site-packages venv/bin/python3 -m nuitka --standalone --recurse-all main.py

After Nuitka ran, attempting to execute ELF:

> 
> host$ ./main.dist/main.exe test
> Traceback (most recent call last):
>   File "/home/user/stuff/main.dist/main.py", line 1, in <module>
>   File "/home/user/stuff/main.dist/uvloop/__init__.py", line 7, in <module uvloop>
>   File "uvloop/loop.pyx", line 35, in init uvloop.loop
> ImportError: cannot import name _noop
> host$ ./venv/bin/python3 main.py test
> ======== Running on http://127.0.0.1:8080 ========
> (Press CTRL+C to quit)
> ^Chost$ 

Full log of Nuitka: 
[nuitka.txt](https://github.com/kayhayen/Nuitka/files/2348174/nuitka.txt)

I also tried creating the venv with --always-copy but didn't help. 

To reproduce:
create venv

> virtualenv -p /usr/bin/python3 venv

Install nuitka & uvloop

> ./venv/bin/pip3 -q install nuitka uvloop

create main.py:
```
import uvloop
print('hello')
```
Compile and attempt to run:

> host$ ./venv/bin/python3 -m nuitka --standalone --recurse-all main.py
> host$ ./main.dist/main.exe 
> Traceback (most recent call last):
>   File "/home/user/stuff/main.dist/main.py", line 1, in <module>
>   File "/home/user/stuff/main.dist/uvloop/__init__.py", line 7, in <module uvloop>
>   File "uvloop/loop.pyx", line 35, in init uvloop.loop
> ImportError: cannot import name _noop
> host$ ./venv/bin/python3 main.py
> hello
> host$

**Comment by pbartyik** [comment]
Not sure if this is what you are looking for, this is my first attempt on making use of Nuitka.
Built with 

> ./venv/bin/python3 -m nuitka --standalone --recurse-all --trace-execution main.py

Results of running:

> user@host:/stuff$ ./main.dist/main.exe 
> main(): Entered.
> main(): Prepare standalone environment.
> Binary dir is /home/user/stuff/main.dist
> main(): Calling convertCommandLineParameters.
> main(): Calling setCommandLineParameters.
> main(): Calling Py_Initialize to initialize interpreter.
> main(): Calling setCommandLineParameters.
> main(): Restore standalone environment.
> Path is '/home/user/stuff/main.dist' (PYTHONHOME /home/user/stuff/main.dist)
> Path is '/home/user/stuff/main.dist'.
> main(): Calling _initBuiltinModule().
> main(): Calling createGlobalConstants().
> Creating constant: const_int_0
> Creating constant: const_str_dot
> Creating constant: const_int_pos_1
> Creating constant: const_str_empty
> Creating constant: const_dict_empty
> Creating constant: const_bytes_empty
> Creating constant: const_tuple_empty
> Creating constant: const_str_plain_rb
> Creating constant: const_str_plain_end
> Creating constant: const_str_plain_get
> Creating constant: const_str_plain_int
> Creating constant: const_str_plain_len
> Creating constant: const_str_plain_sum
> Creating constant: const_str_plain_sys
> Creating constant: const_str_plain_file
> Creating constant: const_str_plain_iter
> Creating constant: const_str_plain_loop
> Creating constant: const_str_plain_name
> Creating constant: const_str_plain_open
> Creating constant: const_str_plain_path
> Creating constant: const_str_plain_read
> Creating constant: const_str_plain_repr
> Creating constant: const_str_plain_self
> Creating constant: const_str_plain_send
> Creating constant: const_str_plain_site
> Creating constant: const_str_plain_type
> Creating constant: const_str_plain_bytes
> Creating constant: const_str_plain_close
> Creating constant: const_str_plain_level
> Creating constant: const_str_plain_print
> Creating constant: const_str_plain_range
> Creating constant: const_str_plain_throw
> Creating constant: const_str_plain_types
> Creating constant: const_str_plain_format
> Creating constant: const_str_plain_locals
> Creating constant: const_str_plain_uvloop
> Creating constant: const_str_plain___all__
> Creating constant: const_str_plain___cmp__
> Creating constant: const_str_plain___doc__
> Creating constant: const_str_plain_asyncio
> Creating constant: const_str_plain_compile
> Creating constant: const_str_plain_dirname
> Creating constant: const_str_plain_environ
> Creating constant: const_str_plain_globals
> Creating constant: const_str_plain_inspect
> Creating constant: const_str_plain___dict__
> Creating constant: const_str_plain___exit__
> Creating constant: const_str_plain___file__
> Creating constant: const_str_plain___iter__
> Creating constant: const_str_plain___main__
> Creating constant: const_str_plain___name__
> Creating constant: const_str_plain___path__
> Creating constant: const_str_plain___spec__
> Creating constant: const_str_plain_fromlist
> Creating constant: const_str_plain_includes
> Creating constant: const_str_plain___class__
> Creating constant: const_str_plain___enter__
> Creating constant: const_str_plain_bytearray
> Creating constant: const_str_plain___cached__
> Creating constant: const_str_plain___import__
> Creating constant: const_str_plain___loader__
> Creating constant: const_str_plain___module__
> Creating constant: const_str_plain___package__
> Creating constant: const_str_plain_classmethod
> Creating constant: const_str_plain___builtins__
> Creating constant: const_str_plain___qualname__
> Creating constant: const_str_plain_staticmethod
> Creating constant: const_str_plain___metaclass__
> Creating constant: const_str_plain_NUITKA_PACKAGE_uvloop
> Creating constant: const_str_digest_12fd368eb47dd7cd0979ad0d5fb56ed4
> Creating constant: const_str_digest_5bfaf90dbd407b4fc29090c8f6415242
> Creating constant: const_tuple_9bc535a5ad26ba550b7fcd540c928114_tuple
> main(): Calling _initBuiltinOriginalValues().
> main(): Calling enhancePythonTypes().
> main(): Calling patchBuiltinModule().
> main(): Calling patchTypeComparison().
> main(): Calling patchTracebackDealloc().
> main(): Calling setEarlyFrozenModulesFileAttribute().
> main(): Calling setupMetaPathBasedLoader().
> main(): Calling patchInspectModule().
> main(): Calling __main__.
> __main__: Calling createModuleConstants().
> Creating constant: const_tuple_str_plain_hello_tuple
> Creating constant: const_str_plain_hello
> Creating constant: const_str_plain___annotations__
> Creating constant: const_str_angle_module
> Creating constant: const_str_digest_f34cdca74fc16abcad2cddea5a06d6ae
> __main__: Calling createModuleCodeObjects().
> Execute: main.py:1 <Node 'STATEMENTS_FRAME_MODULE' with {'code_object': <CodeObjectSpec Module '<module>' with ''>}>
> Execute: main.py:1 <Node 'STATEMENT_EXPRESSION_ONLY'>
> Execute: main.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__doc__' of '__main__'>}>
> Execute: main.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__file__' of '__main__'>}>
> Execute: main.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__cached__' of '__main__'>}>
> Execute: main.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__annotations__' of '__main__'>}>
> Execute: main.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'uvloop' of '__main__'>}>
> uvloop: Calling createModuleConstants().
> Creating constant: const_str_plain_BaseDefaultEventLoopPolicy
> Creating constant: const_str_plain___includes
> Creating constant: const_str_plain_metaclass
> Creating constant: const_str_digest_c68bd7edc718de81b16daba9697d9ed7
> Creating constant: const_str_plain___BasePolicy
> Creating constant: const_str_digest_4e86982459f0d9d8e1407a5103cabdfd
> Creating constant: const_tuple_str_plain___class___tuple
> Creating constant: const_str_plain___class__
> Creating constant: const_str_plain_AbstractEventLoop
> Creating constant: const_str_plain_EventLoopPolicy
> Creating constant: const_str_plain___version__
> Creating constant: const_str_plain__loop_factory
> Creating constant: const_tuple_str_plain_new_event_loop_str_plain_EventLoopPolicy_tuple
> Creating constant: const_str_plain_new_event_loop
> Creating constant: const_tuple_str_plain_includes_tuple
> Creating constant: const_str_plain_includes
> Creating constant: const_str_plain___prepare__
> Creating constant: const_tuple_str_plain_Loop_tuple
> Creating constant: const_str_plain_Loop
> Creating constant: const_tuple_str_plain_self_tuple
> Creating constant: const_str_plain_self
> Creating constant: const_str_digest_57b43d0a1ac2cb813d77e881ae9c9f8e
> Creating constant: const_str_digest_5200dc31fb6903f8c3afa8214146fcc2
> Creating constant: const_str_plain__patch
> Creating constant: const_tuple_str_plain__patch_tuple
> Creating constant: const_str_digest_0c409070500ca19fe4f460b62132e31c
> Creating constant: const_str_digest_077593b90aef305f42ec24f15466fb0a
> Creating constant: const_tuple_str_plain_BaseDefaultEventLoopPolicy_tuple
> Creating constant: const_str_digest_a70bb1eebb38940db22e5bb7d3ccea7e
> Creating constant: const_str_plain___BaseLoop
> uvloop: Calling createModuleCodeObjects().
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/__init__.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__doc__' of 'uvloop'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/__init__.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__file__' of 'uvloop'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/__init__.py:1 <Node 'STATEMENTS_FRAME_MODULE' with {'code_object': <CodeObjectSpec Module '<module uvloop>' with ''>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/__init__.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__path__' of 'uvloop'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/__init__.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__cached__' of 'uvloop'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/__init__.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'asyncio' of 'uvloop'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/__init__.py:3 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__BasePolicy' of 'uvloop'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/__init__.py:5 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__includes' of 'uvloop'>}>
> uvloop.includes: Calling createModuleConstants().
> Creating constant: const_str_plain_threading
> Creating constant: const_str_plain_NUITKA_PACKAGE_uvloop_includes
> Creating constant: const_str_plain_errno
> Creating constant: const_str_plain_time
> Creating constant: const_str_plain_itertools
> Creating constant: const_str_plain_functools
> Creating constant: const_str_digest_c8ff64b7a7832c3652bf72bb02bf650f
> Creating constant: const_str_plain_warnings
> Creating constant: const_str_plain_socket
> Creating constant: const_str_plain_traceback
> Creating constant: const_str_plain_ssl
> Creating constant: const_str_digest_cf6aaf0dfa66843c683b1f36eb60ae6c
> Creating constant: const_str_plain_collections
> Creating constant: const_tuple_174d1616abd4c70e93970879ac8bbd7b_tuple
> Creating constant: const_str_digest_5bfaf90dbd407b4fc29090c8f6415242
> Creating constant: const_str_plain_signal
> Creating constant: const_str_plain_subprocess
> Creating constant: const_str_plain_os
> Creating constant: const_str_digest_cd414fa7160f8d2cba83becd0711e27e
> Creating constant: const_str_plain_stat
> Creating constant: const_str_plain_weakref
> Creating constant: const_str_plain_join
> Creating constant: const_str_plain_gc
> Creating constant: const_str_plain_concurrent
> Creating constant: const_str_digest_34e4086275f7dc880f3fb63f3b91db43
> uvloop.includes: Calling createModuleCodeObjects().
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__doc__' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__file__' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:1 <Node 'STATEMENTS_FRAME_MODULE' with {'code_object': <CodeObjectSpec Module '<module uvloop.includes>' with ''>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__path__' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__cached__' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:4 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'asyncio' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:5 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'collections' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:6 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'concurrent' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:7 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'errno' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:8 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'functools' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:9 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'gc' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:10 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'inspect' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:11 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'itertools' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:12 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'os' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:13 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'signal' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:14 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'socket' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:15 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'subprocess' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:16 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'ssl' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:17 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'stat' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:18 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'sys' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:19 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'threading' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:20 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'traceback' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:21 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'time' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:22 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'warnings' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/includes/__init__.py:23 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'weakref' of 'uvloop.includes'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/__init__.py:6 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '_patch' of 'uvloop'>}>
> uvloop._patch: Calling createModuleConstants().
> Creating constant: const_str_plain_Future
> Creating constant: const_str_plain__wait_for_data
> Creating constant: const_str_plain__transport
> Creating constant: const_tuple_str_plain_coro_str_plain_coro_name_str_plain_running_tuple
> Creating constant: const_str_plain_coro
> Creating constant: const_str_plain_coro_name
> Creating constant: const_str_plain_running
> Creating constant: const_str_digest_c1888cc352b7024f37034cf27f69fc76
> Creating constant: const_str_plain_iscoroutine
> Creating constant: const_str_plain__old_wait_for_data
> Creating constant: const_str_digest_9427bfcc3d441c0de1df2895f4cde733
> Creating constant: const_str_plain__paused
> Creating constant: const_str_plain_resume_reading
> Creating constant: const_str_plain__loop
> Creating constant: const_tuple_str_plain_self_str_plain_func_name_str_plain_create_future_tuple
> Creating constant: const_str_plain_self
> Creating constant: const_str_plain_func_name
> Creating constant: const_str_plain_create_future
> Creating constant: const_tuple_int_pos_3_int_pos_5_int_pos_2_tuple
> Creating constant: const_int_pos_3
> Creating constant: const_int_pos_5
> Creating constant: const_int_pos_2
> Creating constant: const_str_plain_cr_code
> Creating constant: const_tuple_str_plain_coroutines_tuple
> Creating constant: const_str_plain_coroutines
> Creating constant: const_str_digest_a80930fdc6104690b8132519dfe1dd68
> Creating constant: const_str_plain_gi_code
> Creating constant: const_str_digest_55402b4e739cc0bcaa10b55cfe040c9f
> Creating constant: const_str_plain_StreamReader
> Creating constant: const_str_plain__format_coroutine
> Creating constant: const_str_plain_version_info
> Creating constant: const_str_plain_cr_running
> Creating constant: const_str_plain__old_format_coroutine
> Creating constant: const_str_digest_aac2c58b8e1947438c89ba86cab555f8
> Creating constant: const_str_digest_e8cae18ef5e22a6238aeb98d0d25f137
> Creating constant: const_str_digest_a42f4f7d4a3d0d81fd837c0da6326e26
> Creating constant: const_str_plain__eof
> Creating constant: const_tuple_str_digest_55402b4e739cc0bcaa10b55cfe040c9f_tuple
> Creating constant: const_str_digest_1346efefdee8e9e081c5c2a787ea4e1f
> Creating constant: const_str_plain__waiter
> Creating constant: const_tuple_int_pos_3_int_pos_5_int_pos_3_tuple
> Creating constant: const_tuple_str_plain_streams_tuple
> Creating constant: const_str_plain_streams
> Creating constant: const_str_plain_gi_running
> uvloop._patch: Calling createModuleCodeObjects().
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/_patch.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__doc__' of 'uvloop._patch'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/_patch.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__file__' of 'uvloop._patch'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/_patch.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__cached__' of 'uvloop._patch'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/_patch.py:1 <Node 'STATEMENTS_FRAME_MODULE' with {'code_object': <CodeObjectSpec Module '<module uvloop._patch>' with ''>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/_patch.py:1 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'asyncio' of 'uvloop._patch'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/_patch.py:2 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable 'sys' of 'uvloop._patch'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/_patch.py:5 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '_format_coroutine' of 'uvloop._patch'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/_patch.py:30 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '_wait_for_data' of 'uvloop._patch'>}>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/_patch.py:59 <Node 'STATEMENT_CONDITIONAL'>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/_patch.py:65 <Node 'STATEMENT_CONDITIONAL'>
> Execute: /home/user/stuff/venv/lib/python3.6/site-packages/uvloop/__init__.py:7 <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <ModuleVariable '__BaseLoop' of 'uvloop'>}>
> Traceback (most recent call last):
>   File "/home/user/stuff/main.dist/main.py", line 1, in <module>
>   File "/home/user/stuff/main.dist/uvloop/__init__.py", line 7, in <module uvloop>
>   File "uvloop/loop.pyx", line 35, in init uvloop.loop
> ImportError: cannot import name _noop
> user@host:/stuff$ 
>

**Comment by kayhayen** [comment]
There is ways to do this:

The --python-flag=-v outputs requests to the meta path based importer, which for simple cases like this can be good enough.

There is also a "hints" module in the Nuitka source code, which has functions to enable, which would give more information, specifically who is doing this. But in this case there was no doubt.

A fix was pushed to factory and will become part of the next release.

See http://nuitka.net/doc/factory.html if you want to try it.

Yours,
Kay
