### ISSUE TITLE
Report Error : object of type 'generator' has no len()

### ISSUE THREAD

**Issue by coordinate** [kayhayen/Nuitka#118]
> D:\test>nuitka --version
> 0.5.32.7
> 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
> D:\Python37\python.exe

> D:\test>nuitka hello.py
> scons: *** [hello.build\__constants.obj] TypeError : object of type 'generator'
> has no len()
> Traceback (most recent call last):
>   File "D:\Python37\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-
> 3.0.1\SCons\Taskmaster.py", line 241, in execute
>     if not t.retrieve_from_cache():
>   File "D:\Python37\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-
> 3.0.1\SCons\Node\FS.py", line 2925, in retrieve_from_cache
>     return self.get_build_env().get_CacheDir().retrieve(self)
>   File "D:\Python37\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-
> 3.0.1\SCons\Environment.py", line 1016, in get_CacheDir
>     cd = SCons.CacheDir.CacheDir(path)
>   File "D:\Python37\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-
> 3.0.1\SCons\CacheDir.py", line 163, in __init__
>     if os.path.isdir(path) and len(f for f in os.listdir(path) if os.path.basena
> me(f) != "config") != 0:
> TypeError: object of type 'generator' has no len()

Hello.py
`print("Hello")`

**Comment by kayhayen** [comment]
Seems my attempt to fix that scons issue is not working properly. I pushed a fix to factory and will include it in the next release, early next week. It's a race. If you put the len() expression in [] brackets, it will work for you.

**Comment by kayhayen** [comment]
This is in the current pre-release which is become a release any day now, closing therefore.
