### ISSUE TITLE
lxml not built with --file-reference-choice=runtime

### ISSUE THREAD

**Issue by mnunezdm** [kayhayen/Nuitka#127]
Hi!

I'm currently using a python:latest docker image (Python 3.7) with `Linux 4.9.93 linuxkit aufs x86_64 with debian 9.5`

I have tested this with nuitka from pip and from nuitka from develop branch, both have the following version

```sh
$ root@7932a3a6a1f7:/home/test# python nuitka/__main__.py --version
0.5.32.8
3.7.0 (default, Sep  5 2018, 03:25:31)
[GCC 6.3.0 20170516]
/home/test/.direnv/bin/python
```

This are the tests I have done. Using --file-reference-choice=original I can import lxml module but, using --file-reference-choice=runtime, it results in a runtime error

```sh
root@7932a3a6a1f7:/home/test# python nuitka/__main__.py --version
0.5.32.8
3.7.0 (default, Sep  5 2018, 03:25:31)
[GCC 6.3.0 20170516]
/home/test/.direnv/bin/python
root@7932a3a6a1f7:/home/test# python nuitka/__main__.py test.py --recurse-all --file-reference-choice=original
root@7932a3a6a1f7:/home/test# ./test.exe
['hello world\n']
root@7932a3a6a1f7:/home/test# python nuitka/__main__.py test.py --recurse-all --file-reference-choice=runtime
root@7932a3a6a1f7:/home/test# ./test.exe
Traceback (most recent call last):
  File "/home/test/test.py", line 1, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/home/test/lxml/__init__.py)
```

This is the file Im currently using for testing

```python
from lxml import etree

etree.Element('tag')
etree.fromstring('<tag>test</tag>')

with open('hi.txt', 'r') as test_file:
    print(test_file.readlines())
```

I've also tryed to compile it specifying the modules but I get a warning and same error...

```sh
root@7932a3a6a1f7:/home/test# python nuitka/__main__.py test.py --recurse-all --file-reference-choice=runtime --recurse-plugins=lxml.etree
Nuitka:WARNING:Failed to recurse to directory 'lxml.etree'.
root@7932a3a6a1f7:/home/test# python nuitka/__main__.py test.py --recurse-all --file-reference-choice=runtime --include-module=lxml.etree
Nuitka:WARNING:Didn't recurse to 'lxml.etree', apparently not used.
root@7932a3a6a1f7:/home/test# ./test.exe
Traceback (most recent call last):
  File "/home/test/test.py", line 1, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/home/test/lxml/__init__.py)
root@7932a3a6a1f7:/home/test# python nuitka/__main__.py test.py --recurse-all --file-reference-choice=runtime --recurse-plugins=lxml.etree
Nuitka:WARNING:Failed to recurse to directory 'lxml.etree'.
root@7932a3a6a1f7:/home/test# ./test.exe
Traceback (most recent call last):
  File "/home/test/test.py", line 1, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/home/test/lxml/__init__.py)
```

Is there any workaround to solve this?

Kind regards,
Miguel

**Comment by kayhayen** [comment]
Do not use --recurse-plugins for lxml stuff, that is not a plugin directory.

Also I think "runtime" makes it search everything relative to your binary, and then of course it will not find the extension modules. Compiled programs only should use runtime, if they are compiled in standalone mode, that also would be the motivation.

So probably, you are trying to create a binary for use to move to another machine, then --standalone is your friend and the only option you need.

**Comment by mnunezdm** [comment]
Hi!!

Thanks for the quick response, running with standalone seems to fix all the problems.

But, the only bad thing about that param is that instead of a program bundled in a file it creates a directory with all the compiled dependencies, is there any way to bundle into a file as the non-standalone version?

**Comment by kayhayen** [comment]
There is an issue for that #16 but it's not getting any attention. It would be feasible. Want to take it on?
