### ISSUE TITLE
Built-in names could be resolved despite use at module variable

### ISSUE THREAD

**Issue by tibabit** [kayhayen/Nuitka#22]
Hi,

I have some methods in which some parameters have default argument. When I create the executable and run it. It gives following error message.

**TypeError: compile() takes at least 3 arguments (1 given)**
compile functions takes three arguments in which 2 have default values.

I am using following command to create executable
**nuitka --standalone --python-flag=nosite --warn-implicit-exceptions --debug __main__.py**

Any suggestions, what am I doing wrong?

**Comment by kayhayen** [comment]
So do you have a "main.py" to show?

**Comment by tibabit** [comment]
Function is not directly being called from main.py. It is a somewhat large project. So I am including the related files and sections-

**This is the method definition:**
```python
def compile(expression, escape_funcs=None, unescape_funcs=None):                                                                                  
    """ 
    Compile grammar (given as regex string), returning a `CompiledGrammar`
    instance.
    """
    return _compile_from_parse_tree(
        parse_regex(tokenize_regex(expression)),
        escape_funcs=escape_funcs,
        unescape_funcs=unescape_funcs)
```
refer [compiler.py](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/contrib/regular_languages/compiler.py#L392)

And this is the calling script

```python
from __future__ import unicode_literals

from prompt_toolkit.contrib.regular_languages.compiler import compile

from .commands import get_commands_taking_locations


#: The compiled grammar for the Vim command line.
COMMAND_GRAMMAR = compile(r"""
    # Allow leading colons and whitespace. (They are ignored.)
    :*
    \s*
    (
        # Commands accepting a location.
        (?P<command>%(commands_taking_locations)s)(?P<force>!?)  \s+   (?P<location>[^\s]+)
    """)
```
refer [Grammer.py](https://github.com/jonathanslenders/pyvim/blob/master/pyvim/commands/grammar.py#L9)

**Comment by kayhayen** [comment]
I think you reported an issue already fixed in a hotfix release a while go. Please try out the last stable release and re-open if necessary
