### ISSUE TITLE
Visual Studio 2017 not detected

### ISSUE THREAD

**Issue by EinderJam** [kayhayen/Nuitka#23]
Hello,i have some trouble trying to get nuitka 0.5.26.4 working.
I have : 
-VS 2017 community edition
-Python 3.6 32bits
-Python 2.7.13
I try to compile this hello_world script.py :
`print("hello_world")
`
Using this command : 
`nuitka --standalone --recurse-all --python-version=3.6 hello_world.py`
Which gives me 
`Error, cannot locate suitable C compiler. You have the following options:

a) If a suitable Visual Studio version is installed, it will not be located
   automatically, unless you install pywin32 for the Python installation
   below "c:\Python27".

b) To make it find Visual Studio execute from Start Menu the 'Visual Studio
   Command Prompt' or "vcvarsall.bat". That will add Visual Studio to the
   PATH. And it will be detected.

c) Install MinGW64 to "C:\MinGW64" or "\MinGW", where then it is automatically
   detected or add it to PATH before executing Nuitka. But be sure to pick the
   proper variant (32/64 bits, your Python arch is x86).

d) Set the environment variable C to the *full* path of either "gcc.exe". Also
   be sure to head proper architecture or else errors will occur.`

I installed pywin32 on python 2.7 using:
`pip2.7.exe install pypiwin32`
I tried to run vcvarsall.bat x86,amd64,and x86_amd64,with no results.
Have you got any idea ?

**Comment by kayhayen** [comment]
First, use the compilers mentioned in the user manual, they work.

Second, Scons has a table of registry paths to scan for each MSVC version. It stops at the one before 2017. Last I checked, it wasn't updated yet. But it seems the release was done, so might be better now.

After running vcvarsall.bat, is there no "cl.exe" in the PATH? This used to work and I believe I had a recent mention to me that this helped getting MSVC 2017 to work.

If you want to help, you can look at:

./nuitka/build/inline_copy/lib/scons-2.3.2/SCons/Tool/MSCommon/vs.py
./nuitka/build/inline_copy/lib/scons-2.3.2/SCons/Tool/MSCommon/vc.py

It should be relatively easy to figure out a patch that adds MSVC 2017.

Yours,
Kay

**Comment by EinderJam** [comment]
Thanks for your answer !
for vcvarsall.bat,I verified 3 times and there's nothing related to VS in PATH,either User path or system path.
I added myself the path to cl.exe to see if it solves the problem.I also downloaded MinGW64 (msys build because mingw-builds can't be installed,it can't dowload the files it needs) and installed it to C:\MinGW64

And I have another issue now :

`C:\Users\Clément\AppData\Local\Programs\Python\Python36-32\Scripts>nuitka --standalone --recurse-all --python-version=3.6 helloworld.py
Traceback (most recent call last):
  File "C:\Users\Clément\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\nuitka\freezer\Standalone.py", line 245, in _detectImports
    command = command.encode("ascii")
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 38: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Clément\AppData\Local\Programs\Python\Python36-32\Scripts\nuitka", line 204, in <module>
    MainControl.main()
  File "C:\Users\Clément\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\nuitka\MainControl.py", line 708, in main
    for module in detectEarlyImports():
  File "C:\Users\Clément\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\nuitka\freezer\Standalone.py", line 482, in detectEarlyImports
    technical     = True
  File "C:\Users\Clément\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\nuitka\freezer\Standalone.py", line 256, in _detectImports
    os.unlink(tmp_filename)
PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\CLMENT~1\\AppData\\Local\\Temp\\tmpotxflnbd'

C:\Users\Clément\AppData\Local\Programs\Python\Python36-32\Scripts>`

The file in temp is created at runtime by nuitka,so i don't know why any other program would be using it...

**Comment by kayhayen** [comment]
Seems Nuitka wants for Python3 only ascii "sys.path", which is of course a bit demanding. If you change the crashing like from "ascii" to "uft8" it will work. I am going to release a fix on factory branch shortly.

**Comment by kayhayen** [comment]
I did install MSVC 2017 and it seems to break my existing MSVC 2015 installation. I will try and see if the MSVC 2017 works. It should be easy to add and it's what people can download currently, so this will be asked a lot. MinGW64 is easier indeed.

**Comment by EinderJam** [comment]
I have mingw64.exe and mingw32.exe under C:\MinGW64,so it should be good for nuitka,when the other bugs will be fixed

**Comment by kayhayen** [comment]
Seems to work: http://nuitka.net/doc/factory.html

That will have the unicode issue fixed. Generally Nuitka should work with unicode paths, but apparently that one slipped in. Let me know if it sufficient or report more unicode path issues here.

**Comment by EinderJam** [comment]
and another UnicodeDecodeError,with setup.py this time:

`C:\Users\Clément>pip -V
pip 9.0.1 from c:\users\clément\appdata\local\programs\python\python36-32\lib\site-packages (python 3.6)

C:\Users\Clément>pip install -U "http://nuitka.net/gitweb/?p=Nuitka.git;a=snapshot;h=refs/heads/factory;sf=tgz"
Collecting http://nuitka.net/gitweb/?p=Nuitka.git;a=snapshot;h=refs/heads/factory;sf=tgz
  Downloading http://nuitka.net/gitweb/?p=Nuitka.git;a=snapshot;h=refs/heads/factory;sf=tgz
     - 2.4MB 147kB/s
Installing collected packages: Nuitka
  Running setup.py install for Nuitka ... error
Exception:
Traceback (most recent call last):
  File "c:\users\clément\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 60: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\clément\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\clément\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\clément\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\clément\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\clément\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\clément\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 60: invalid continuation byte`

**Comment by kayhayen** [comment]
The unicode crash seems to be in "pip" purely. Likely they have similar issues. Maybe only code is affected that downloads like this, or all pip installs are?

Anyway, good news is, I just pushed 2017 support for Nuitka and make the pre-release this morning, just use that then. This of course also includes the unicode fix then. If anything in that real appears.
