### ISSUE TITLE
working with virtualenvwrapper?

### ISSUE THREAD

**Issue by mehmetkose** [kayhayen/Nuitka#24]
Hi everyone!,
I couldn't figure out how can I use with virtualenvwrapper. Can anyone show an example?
Thanks.

**Comment by kayhayen** [comment]
Please make it clear where the user manual is lacking or what happens when you tried.

**Comment by mehmetkose** [comment]
![ekran resmi 2017-07-16 12 46 17](https://user-images.githubusercontent.com/706678/28246533-d1ea4342-6a24-11e7-87b9-b0b808359f22.png)
I tried like this

**Comment by kayhayen** [comment]
How certain are you that nuitka is running with that virtualenv's Python there? Did you install it from pip too?

**Comment by kayhayen** [comment]
Lack of feedback.
