### ISSUE TITLE
UnicodeEncodeError "ascii codec can't encode....." when installing develop version of nuitka

### ISSUE THREAD

**Issue by EinderJam** [kayhayen/Nuitka#25]
hello again ! I saw your fixes,and of course i tried to install the develop version of nuitka,but without pip this time.
I downloaded the zip on my desktop,extracted it,and did : 'python.exe setup.py install'
the output is here : https://pastebin.com/7BYAUcbW
EDIT: modifying 'ascii' to 'utf-8' in easy_install.py allows the installation to complete,but nuitka can't run then : calling nuitka with any option (--help,--standalone) doesn't return anything.

**Comment by kayhayen** [comment]
Trying to reproduce this, I just got:

> Running virtualenv with interpreter /usr/bin/python2
> New python executable in /data/home/hayen/test/ü/venv/bin/python2
> Also creating executable in /data/home/hayen/test/ü/venv/bin/python
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 22: ordinal not in range(128)
> ERROR: The executable /data/home/hayen/test/ü/venv/bin/python2 is not functioning
> ERROR: It thinks sys.prefix is u'/data/home/hayen/test/\xfc' (should be u'/data/home/hayen/test/\xfc/venv')
> ERROR: virtualenv is not compatible with this system or executable

Does not seems like a very well supported thing, however with -p python3.6 that part worked.

**Comment by kayhayen** [comment]
Ok, this was caused by issue#301 on "bugs.nuitka.net", where the "develop" command was supposed to be hacked, so it doesn't do crap. No idea, why that changes "install" too, but it does. I am making a guard around it, so it's only used when "develop" is actually used.

**Comment by kayhayen** [comment]
So, I am pushing this to factory, thanks for the report.
