### ISSUE TITLE
.pyd file produced not .so

### ISSUE THREAD

**Issue by mfaraj57** [kayhayen/Nuitka#26]
Hello
I used Nuitka in windows 10 environment 64bit with visual studio 15 installed and python 2.7xx.
i used command line on shell as written in documentation to produce .so file
` nuitka --module myplugin.py`
everything going ok without error messages but the file produced with extension .pyd
The file is ok in windows and i can import functions from it to other python modules.
but i want to use the file in project python  in small Linux environment in enigma2 box(like dreambox),i tried to use the .pyd file in this Linux environment but failed to import functions(could not import  myplugin.pyd),but i know my small linux enviroment can manage .so file
Is there way to produce  .so file in windows or i have to use linux(my small box small linux can not manage Nuitka) and i do not have standard pc linux for now)?

**Comment by mfaraj57** [comment]
I made  .so file in linux 32bit pc and tested the file in linux and it is ok.But i want to use the file with MIPS receiver(e.g dreambox) with linux environment but when tested the ,so file i had this error
`ImportError: /var/volatile/tmp/printtext.so: cannot open shared object file: No
such file or directory` 
Is there way to compile the python module to produce MIPS specific .so file?

**Comment by kayhayen** [comment]
You need to use a MIPS Linux PC with a matching Python installation. Cross compilation is not supported. You could use a qemu image, e.g. from qemu-system-mips, but I won't help you with that, sorry.
