### ISSUE TITLE
nuitka fails to find C include files

### ISSUE THREAD

**Issue by krisk0** [kayhayen/Nuitka#27]
Tried nuitka-0.5.27 on Gentoo/AMD.

nuitka fails to compile 2-line program `import numpy;print numpy.zeros([2,2])`

Lots of warnins like 
```
Nuitka:WARNING:/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py:72: Cannot find 'pkg_resources.extern.packaging.markers' in package 'pkg_resources' as absolute import.
```
and
```
Nuitka:WARNING:Unresolved '__import__' call at '/usr/lib64/python2.7/site-packages/six.py:82' may require use of '--recurse-directory'.
```
Then multiple error messages like
```
n.build/__frozen.cpp(3): catastrophic error: cannot open source file "Python.h"
  #include <Python.h>
                     ^

compilation aborted for n.build/__frozen.cpp (code 4)
n.build/__helpers.cpp(4): catastrophic error: cannot open source file "nuitka/prelude.h"
  #include "nuitka/prelude.h"
                             ^
```

List of installed nuitka files (truncated for readability):
```
/usr
/usr/bin
/usr/bin/nuitka
/usr/bin/nuitka-run
/usr/lib
/usr/lib/python-exec
/usr/lib/python-exec/python2.7
/usr/lib/python-exec/python2.7/nuitka
/usr/lib/python-exec/python2.7/nuitka-run
/usr/lib64
/usr/lib64/python2.7
/usr/lib64/python2.7/site-packages
/usr/lib64/python2.7/site-packages/Nuitka-0.5.27-py2.7.egg-info
/usr/lib64/python2.7/site-packages/Nuitka-0.5.27-py2.7.egg-info/PKG-INFO
/usr/lib64/python2.7/site-packages/Nuitka-0.5.27-py2.7.egg-info/SOURCES.txt
/usr/lib64/python2.7/site-packages/Nuitka-0.5.27-py2.7.egg-info/dependency_links.txt
/usr/lib64/python2.7/site-packages/Nuitka-0.5.27-py2.7.egg-info/top_level.txt
/usr/lib64/python2.7/site-packages/nuitka
/usr/lib64/python2.7/site-packages/nuitka/Builtins.py
/usr/lib64/python2.7/site-packages/nuitka/Builtins.pyc
...
/usr/lib64/python2.7/site-packages/nuitka/build/__init__.pyo
/usr/lib64/python2.7/site-packages/nuitka/build/include
/usr/lib64/python2.7/site-packages/nuitka/build/include/coro.h
/usr/lib64/python2.7/site-packages/nuitka/build/include/nuitka
/usr/lib64/python2.7/site-packages/nuitka/build/include/nuitka/allocator.h
...
/usr/lib64/python2.7/site-packages/nuitka/build/include/nuitka/prelude.h
...
/usr/lib64/python2.7/site-packages/nuitka/utils/__init__.pyo
/usr/share
/usr/share/doc
/usr/share/doc/nuitka-0.5.27
/usr/share/doc/nuitka-0.5.27/README.rst.lzma
```

Whereabouts of **Python.h**:
```
/usr/include/python2.7/Python.h
/usr/include/python3.4m/Python.h
/usr/lib64/pypy/include/Python.h
... (android and macos stuff skipped)
```

If more information from me is required, I will of course provide it.

**Comment by kayhayen** [comment]
Can you provide the output for scons, using the --show-scons making sure that the ".build" directory is deleted, so no caching will be going on.

In "SingleExe.scons" there is a check that will be happy with  /usr/include/python2.7/Python.h I suppose, and then that directory is added to the PATH. With the scons output, I will be able to tell, if anything strange is going on.

And of course, this won't be working for even hello world, there is a systematic issue there I suppose.

**Comment by krisk0** [comment]
kayhayen, thank you for help. 

I added `--show-scons` to nuitka command-line. Noticed that nuitka tried to use Intel icc compiler. Consulted `nuitka --help` output and found no way to tell it to use gcc. Hid icc compiler so nuitka would not find it.

After that, the 2 lines of code compiled successfully. Output of the executable is correct.

I have multiple versions of gcc installed. Is it possible to tell nuitka exactly which of them should be used?

If there is no such feature in nuitka, I suggest that it is implemented.

**Comment by kayhayen** [comment]
Nuitka respects the "CC" variable. Using CC=/usr/bin/gcc ought to work.

The "icc" compiler ought to be supported by Scons though. Can you find out, why it doesn't get the include path handed over? Are you using the builtin copy from Nuitka or an installed latest greatest version of scons?

If the "icc" cannot work, I would like to know and disable it for Nuitka.

**Comment by krisk0** [comment]
I got dev-util/scons-2.3.4 installed, don't know how great it is.

I wonder whether a good .ebuild script for nuitka exists (better than my https://gist.github.com/krisk0/d7f66cb5339894c1c92456785470288a).

My icc is very old and nuitka probably wants a capable compiler. And I don't want to compile my python code with icc.  For these reasons, I won't test icc under nuitka. Sorry.

It's good that I can test multiple gcc and clang compilers, thank you for the CC hint.

// nuitka and pyinstaller both work for me. nuitka is a lot slower than pyinstaller when compiling code, but pyinstaller-created executable puts some garbage into my /tmp while nuitka-created executable behaves normally. Still need to check which of them runs faster.
