### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JohannesTK** [kayhayen/Nuitka#28]
![image](https://user-images.githubusercontent.com/3767980/29059377-f186fee2-7c1d-11e7-97f9-1f6c62bb72d2.png)

![image](https://user-images.githubusercontent.com/3767980/29059382-fa66e6bc-7c1d-11e7-8e34-101f20acc527.png)

![image](https://user-images.githubusercontent.com/3767980/29059427-2df24878-7c1e-11e7-86bc-8d4b023e5138.png)

Nuitka version: 0.5.26.4

This is fixed with nuitka version: 0.5.27 so I guess it isn't a high priority. 0.5.27 in repositories would be great though. 

And by the way thanks for the great work!

**Comment by kayhayen** [comment]
Wasn't so sure what you meant with repositories, I updated PyPI, which was broken due to wrong classifier, should be good now.
