### ISSUE TITLE
ImportError with multiprocessing

### ISSUE THREAD

**Issue by JohannesTK** [kayhayen/Nuitka#30]
ImportError with multiprocessing:

```
./process.exe 
Traceback (most recent call last):
  File "/home/ubuntu/thread_test/process.py", line 3, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/usr/lib/python3.5/concurrent/futures/__init__.py", line 17, in <module>
    from concurrent.futures.process import ProcessPoolExecutor
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 55, in <module>
    from multiprocessing.connection import wait
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 21, in <module>
    import _multiprocessing
ImportError: /home/ubuntu/thread_test/_multiprocessing.so: cannot open shared object file: No such file or directory
```

Code to reproduce: 

```python
#!/usr/bin/env python3

from concurrent.futures import ProcessPoolExecutor
from time import sleep
 
def thread(msg):
    sleep(1)
    print("Message: {}".format(msg))
 
pool = ProcessPoolExecutor(2)
 
future = pool.submit(thread, "I have my own GIL")
print(future.done())
sleep(2)
print(future.done())
```

Compile with: 
```
nuitka --standalone --python-flag=no_site --python-version=3.5 process.py
```

The culprit seems to be the --standalone argument as this works fine: 
```
nuitka --recurse-all --python-flag=no_site --python-version=3.5 process.py
```

``` 
Nuitka version: 0.5.27
Python 3 version: 3.5.2
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by JohannesTK** [comment]
Solved with having the _multiprocessing.so shared object from process.dist at the same directory as the process.exe.

In doc it's stated:

> If you want to be able to copy it to another machine, use --standalone and copy the created program.dist directory and execute the program.exe put inside.

The standalone binary have worked fine without the shared objects in program.dist directory until using the multiprocessing module. In that case the other shared objects are statically linked except the multiprocessing which needs runtime linking?

**Comment by kayhayen** [comment]
All C extension modules are put into the ".dist" folder, as are the DLLs used by them, yes. Not having them will cause errors.

What wording would help you to understand better?
