### ISSUE TITLE
Not working on Windows 10 VS 2017

### ISSUE THREAD

**Issue by douglasmccormickjr** [kayhayen/Nuitka#31]
I created a very simple python script:
`print("hi there")`

...and I typed this in the command line to get it to compile within nuitka:

`nuitka --standalone hithere.py`

This is the error I'm getting:

```
Traceback (most recent call last):
  File "C:\Python36\Scripts\nuitka", line 211, in <module>
    MainControl.main()
  File "C:\Python36\Lib\site-packages\nuitka\MainControl.py", line 766, in main
    main_module = main_module
  File "C:\Python36\Lib\site-packages\nuitka\MainControl.py", line 682, in compileTree
    quiet       = not Options.isShowScons()
  File "C:\Python36\Lib\site-packages\nuitka\MainControl.py", line 549, in runScons
    return SconsInterface.runScons(options, quiet), options
  File "C:\Python36\Lib\site-packages\nuitka\build\SconsInterface.py", line 266, in runScons
    return subprocess.call(scons_command, shell = False) == 0
  File "C:\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

My system info (if you're curios):
 - Windows 10
 - Python 3.6 & Python 2.7.13 (both 64bit)
 - C:\MinGW64 installed in that pathway
 - CC pathway setup correctly for gcc.exe
 - Latest version of Nuitka (used the MSI download) - 0.5.27
 - I was tying to compile originally via python 2.7 (I was getting the message of "Error, cannot locate suitable C compiler. You have the following options:" although I did follow those steps) -- I'm happy that its just throwing some strange Windows error looking for something instead of the other problem

I wish I could just get a VM with this working on it so I didn't have to jump through these steps to not really progress at all.

**Comment by kayhayen** [comment]
You fail to run Scons. And apparently the Python2 there. Can you make it print out the command used in C:\Python36\Lib\site-packages\nuitka\build\SconsInterface.py and confirm that the file does not exist?

If I were to guess, you might have installed a Python2 and removed it, but not from registry, just from disk or so. The scanning would have to be made more robust against considering non-found binaries as existing.

**Comment by kayhayen** [comment]
Lack of feedback.
