### ISSUE TITLE
switch to scons 3.0?

### ISSUE THREAD

**Issue by AlJohri** [kayhayen/Nuitka#33]
seems like scons 3.0 is now python 3 compatible: https://bitbucket.org/scons/scons/src/rel_3.0.0/src/CHANGES.txt?at=3.0.0&fileviewer=file-view-default

this can simplify the requirements: https://github.com/kayhayen/Nuitka#requirements

**Comment by kayhayen** [comment]
Hello there,

yes, definitely will try this out and then include both scons versions, for
as long as that is feasible. Using the current thing for either 2.6 only,
or all of Python2, and the new thing for Python3. Not so sure, how
compatible they are for scons files and tricks Nuitka plays there. That
will of course improve the out of the box experience big time.

Yours,
Kay

**Comment by AlJohri** [comment]
Great thanks! I think dropping 2.6 might end up being a considerably easier approach and perhaps time within the next year. https://github.com/pypa/pip/issues/3955

**Comment by kayhayen** [comment]
The 2.6 support will be there even afterwards. It seems however that Scons 3.0.0 didn't change anything, and just works with what is currently on develop branch. I didn't make the Python2 and use search go away. But I was getting errors for the print statements, and fixing that seemed to make it work. I will look into this deeper after a soon coming release. Before embedding it, maybe waiting for a 3.0.1 might make sense.

**Comment by kayhayen** [comment]
Also Scons only supports Python 3.5 or higher. So for 3.2 and 3.3, not only will Nuitka still have to fork a new process, also it will need a Python 3.5 or 3.4 or Python2 installation, which is totally ugly, but of course workable.

**Comment by kayhayen** [comment]
I just pushed to factory the necessary changes, should work now. The doc updates, and a fixup for MinGW is coming soon there too. Closing this.

**Comment by AlJohri** [comment]
Thanks @kayhayen!
