### ISSUE TITLE
Py3 module

### ISSUE THREAD

**Issue by ThomasLecocq** [kayhayen/Nuitka#34]
Hi,

This line: 
https://github.com/kayhayen/Nuitka/blob/develop/nuitka/build/SingleExe.scons#L1067

raises an error on Py3, because the output of 
```defs, stderr = proc.communicate()```

are bytes, and bytes can't be written directly to files. 
It should be something like:
```python
defs_file.write(defs.decode("utf-8"))
```

but not sure how to insure py2 compat.

**Comment by kayhayen** [comment]
Yes, indeed. For me and testers most probably the caching of the result prevented this from happening, expect a hotfix soon.

Typically this is done like this:

```
    if str is not bytes:
        defs = defs.decode("utf8")
```

**Comment by ThomasLecocq** [comment]
ah yes, good way to keep Py2 and Py3 compat! 
Cheers!

**Comment by kayhayen** [comment]
Part of the hotfix the other day.

**Comment by ThomasLecocq** [comment]
@kayhayen thanks. NB you should give the commit number rather than "the other day" :) but it's ok now, I've installed the develop branch and could successfully build an extension, thanks!
