### ISSUE TITLE
Issue compiling six.move.http_client

### ISSUE THREAD

**Issue by Pckool** [kayhayen/Nuitka#37]
So I'm new to Nuitka and I am loving it so far but there is one major issue I am coming across. Every time I compile my program, it runs into an issue importing a major piece of one of the imported packages (tweepy) For some reason it has trouble importing six.move.http_client, but when running the program with the python interpreter there are no issues. I would really love some help in fixing this issue. If you need any assets let me know and I will get them for you.
Kind regards.

**Comment by kayhayen** [comment]
Can you provide a minimal reproducer?

**Comment by Pckool** [comment]
Warnings given (failed imports with the command on the very top of the cmd): https://imgur.com/ic4y90w
I also placed the minimal producer in this zip file. Sorry about how scrappy it looks, I pieced it together from my original code but it basically does the same thing minus the ui and saving the consumer keys.

[test.zip](https://github.com/kayhayen/Nuitka/files/1471068/test.zip)

**Comment by kayhayen** [comment]
Hello there,

are you saying that the warnings are the issue, or do you also have any runtime issue?

Yours,
Kay

**Comment by Pckool** [comment]
There is a runtime issue as well. Whenever the oauth tries to grab the clients token, it crashes the application. This seems to be because six.move.http_client is having issues being imported. That is the only thing I can think of.

**Comment by kayhayen** [comment]
This is an issue with "requests" and Nuitka in an older version. I reproduced it on my Debian Stretch, but not on one machine where I had an upgraded requests, albeit not recently. It seems the module aliasing needs expansion, or else "exceptions" is failing there.

This is a bit fiddly, but I hope to sort it out for a future release.

**Comment by Pckool** [comment]
Is there anything I can do at this point to fix the issue on my end or is this a compiler issue that I am unable to resolve.

**Comment by kayhayen** [comment]
No, not at all. I have resolved the requests issue in my working copy, but I also have one with "import six.moves" which doesn't include "six", that will also need to be dealt with, and the actual moves need to be added as well. I will put out something on the factory branch eventually and let you know, when to test it.

Seems this is closing gaps on the import mechanism as well as providing workarounds for meta path based importer chaos. But it seems workable, I expect to have something on the weekend.

**Comment by Pckool** [comment]
Good to hear! I’m glad I helped find a potential patch to an issue for your compiler. It honestly is an amazing tool and fantastic for distribution, so I really want to see nuitka reach all its goals and work at its best!

**Comment by kayhayen** [comment]
This was released as part of the hotfix just now. Please allow a few days for packages to update.
