### ISSUE TITLE
Not supported: WebAssembly(wasm)

### ISSUE THREAD

**Issue by appcypher** [kayhayen/Nuitka#41]
It's a beautiful project you have here. I admire it quite a lot and come around once in a while to learn from it even though I don't use it directly in my work. 
I understand the core developer of this project may have a lot on his plate but I've often wondered if Nuitka could have a wasm codegen phase.
The idea of having Python run in the browser is fascinating and I can't wait to see the possible applications of it. I, for one, would love to write some of my web apps in Python, I believe a lot of people would too.
I know my way around wasm and wast and I could help out with the codegen, but if there is a reason this idea won't work I would like to know.

**Comment by kayhayen** [comment]
Nuitka depends on "libpython" to work. If you can load that, it's fine, but I doubt it.

**Comment by rafi16jan** [comment]
libpython is a C library right? isn't Webassembly compiles a LLVM compatible code (and its dependencies) to byte code? I want to try this

**Comment by kayhayen** [comment]
@rafi16jan Go ahead, you are welcome.

**Comment by kayhayen** [comment]
Meh, cannot assign you, but consider yourself in charge until you give up @rafi16jan

**Comment by rafi16jan** [comment]
Ok, I'll report

**Comment by kayhayen** [comment]
Thanks for reporting. I do not mind reading good things about PyPy, which is behind RPython. I think it is good for what it does. I actually once contributed a small patch to it, a decade ago. :)

I am putting this to unsupported then, leaving the question tag, so people will find it.

**Comment by rafi16jan** [comment]
Can you (or maybe the right question is, do you have time :D) to give us newbies guide/advice to debug this RPython and the C source it generated. We younglings aren't like you guys that can understand C the same way we understand Python. It's heaven and earth to us (maybe hell). We're generation that aren't used to compile things, unless it is java or .net haha

**Comment by kayhayen** [comment]
Not enough time for Nuitka as it stands.

**Comment by rafi16jan** [comment]
Ok I understand

**Comment by CrazyPython** [comment]
@rafi16jan I know a bit of C, I’m willing to help.

**Comment by CrazyPython** [comment]
Maybe we can ask on the PyPy mailing list.

**Comment by rafi16jan** [comment]
@CrazyPython Nice, where we start?

**Comment by rafi16jan** [comment]
@wolfv Sorry for tagging you hehe, how's your experience with the new MicroPython javascript port?

**Comment by wolfv** [comment]
It's quite straightforward nowadays to compile to webassembly. you just need to know which functions to export.
Nowadays you should also be able to find libpython compiled to webassembly. however, it will be much larger than micropython (which is the big advantage). MicroPython compiled is only ~200kb, so in the same range as modern JS frameworks.

**Comment by rafi16jan** [comment]
@wolfv Is there already a way to interact with DOM or WebAPIs? Because I ask another port to WASM what's the difference between his port and the official port, he promises that he will add DOM interaction and even asyncio support with requestAnimationFrame. Take a look at [this](https://github.com/pmp-p/micropython-ports-wasm/issues/4)

**Comment by rafi16jan** [comment]
Not related to Nuitka, but I have make an ES6 Module of the official MicroPython WASM port. https://www.npmjs.com/package/micropython

@appcypher @ids1024 @CrazyPython

**Comment by pmp-p** [comment]
> Nuitka depends on "libpython" to work. If you can load that, it's fine, but I doubt it.

@kayhayen libpython3.8.a is (now) easy to build with clang 10 ( emsdk tot-upstream ) and i did not find any problem running standard stdlib python code in repl. 

https://pmp-p.github.io/python-next/test.html  patches here https://github.com/pmp-p/pydk/tree/master/sources.em

If anyone would like to experiment Nuitka on that lib i'm ready to help ( i'm on gitter and freenode )

@rafi16jan i made the asyncio micropython DOM support compatible with cpython too with the same module see the test page above.

**Comment by dhiahassen** [comment]
@pmp-p  @rafi16jan  @wolfv @CrazyPython   , i am a very experienced C/C++ programmer , i will be there for help for any C/C++ related things

**Comment by rafi16jan** [comment]
> @pmp-p @rafi16jan @wolfv @CrazyPython , i am a very experienced C/C++ programmer , i will be there for help for any C/C++ related things

Great! Months ago I've successfully fork RPython to be able to compile to WASM. Please give any feedback here https://github.com/rafi16jan/rpython-wasm

I would like to see someone continue the work since I'm busy with other things right now
