### ISSUE TITLE
Issue with compiling 

### ISSUE THREAD

**Issue by linktlh** [kayhayen/Nuitka#49]
*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
0.5.28.1 python 2.7.5 Windows 10

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.
I used pip install nuitka python came with panda3d

*  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces
      the issue and can be run with out any other (or as few as possible)
      external dependencies.
I tried using roaming-ralph in the panda3d samples folder, however I keep getting this error no matter what. 

* Command Used: 
`nuitka --standalone --recurse-all --verbose --enhanced --output-dir=build --python-version=2.7 main.py`

* Error:
```
Traceback (most recent call last):
  File "c:\users\link\appdata\local\temp\tmphla8bk", line 20, in <module>
    __import__(imp)
  File "C:\Panda3D-1.10.0\panda\python\lib\smartroom\BeyondQuestion.py", line 139, in <module>
    createPort()
  File "C:\Panda3D-1.10.0\python\lib\smartroom\BeyondQuestion.py", line 66, in createPort
    raise "The Beyond Question Executable is not installed properly."
TypeError: exceptions must be old-style classes or derived from BaseException, not str
```

_I'm not entirely sure if this is a bug, or if I'm just doing something wrong. thanks in advance for any help._

**Comment by kayhayen** [comment]
One thing is for sure, the code seems to make checks that are not fulfilled, and then raises an exception in the wrong way. Without looking at "BeyondQuestion.py" we will not know what it is. Can you identify what the criterion for that "raise" to happen is?

**Comment by linktlh** [comment]
Whoops, I meant to close this, Nuitka defaulted to my 1.9.0 build of panda3D but my program was made for the 1.10.0 version with astron lib.
