### ISSUE TITLE
Python3.6 in Cygwin x64 in Windows 10: weird compile error

### ISSUE THREAD

**Issue by thjwong** [kayhayen/Nuitka#52]
In installed Nuitka via pip because of the good words about when Nuitka can do.

Perhaps my setting is not so canonical: Windows 10 x64, and Python3.6 from within Cygwin x64. The script works without any problem.
But when I run 
$> nuitka --recurse-all --python-version=3.6 myPythonScript.py
There is this error message:
$> nuitka --recurse-all --python-version=3.6 myPythonScript.py
Traceback (most recent call last):
  File "/usr/bin/nuitka", line 74, in <module>
    from nuitka import Options                  # isort:skip
ModuleNotFoundError: No module named 'nuitka'

I even started pip inside Python 3 and installed isort, but that didn't help.

Please let me know I should do to assist the improvement of Nuitka.

**Comment by kayhayen** [comment]
The Cygwin is unsupported, see #35 for details.

The other error will be fixed in an upcoming release, it currently lives on the factory branch. I am closing this issue as a duplicate.
