### ISSUE TITLE
Compiling: Need to have an option to force inclusion of modules

### ISSUE THREAD

**Issue by voarsh** [kayhayen/Nuitka#55]
*  Nuitka version: 0.5.28.1
*  Full Python version: 2.7.13
* Platform: Windows
*  How did you install Nuitka: pip
* Python from source, Panda3D (panda3d.org)
 
I am trying to compile Panda3D and my code.

I have added 
```python
from direct.distributed import * 
```
to the start file and it still does not compile everything in the direct.distributed folder, but it still includes some files from it.

When I run nuitka --standalone --recurse-all --recurse-to=direct.distributed.DistributedCartesianGrid.py --verbose --enhanced --output-dir=build --show-progress --python-version=2.7 main.py

I get a printout saying "Nuitka:WARNING:Didn't recurse to 'direct.distributed.DistributedCartesianGrid.py', apparently not used." However, after building, the program clearly tries to load this file, and to no surprise, it is not found (because Nuitka didn't include it).

Any tips?

**Comment by kayhayen** [comment]
The recurse options control only visible imports. They do not force any inclusion. For that I am adding options --include-* in a coming release. Until then, just make an explicit import in your main program or whereever Nuitka will see it.

I am leaving this open for reference when the include options will be ready.

**Comment by kayhayen** [comment]
So these inclusion options are in the factory branch.

For you --include-module=direct.distributed.DistributedCartesianGrid should do the trick.

I am expecting to make a new release with the feature relatively soon.

**Comment by kayhayen** [comment]
Released as 0.5.30
