### ISSUE TITLE
Boostrap issue when running generated exe

### ISSUE THREAD

**Issue by mattvend** [kayhayen/Nuitka#62]
* Nuitka version: 0.5.29rc4
* Python version: Python 3.6.1 Anaconda
* Windows 10
* Nuitka downloaded from site and installed from Nuitka-5.0.2940.win-amd64.py36.msi
* I am using a virtual env

I am freezing a python command line program. I had to update to the RC version as Nuitka-5.1.281.win-amd64.py36.msi was not able to freeze the program (same warning messages as issue#60, can not find ... as absolute import, executable not generated).  

0.5.29RC 4 generates the executable, but once called it fails.

The error message is the following:
`    import numpy as np  `
`  File "<frozen importlib._bootstrap>", line 961, in _find_and_load  `
`  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked  `
`  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked  `
`  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible  `
`KeyError: 'numpy'  `
`Traceback (most recent call last):  `

I checked that numpy was already installed in the virtual environment, there is no problem.
There was another module giving the same issue. I placed the python module file next to executable and the issue is gone.

Please tell me what other checks I can do to solve the issue.

**Comment by kayhayen** [comment]
Can you come up with a minimal reproducer please?

**Comment by mattvend** [comment]
If I put it in a private repository, is it ok for you ?

**Comment by mattvend** [comment]
Issue seems more complex than I thought.

If I build my program, not using any virutal env on my machine but the system wide Python, then it works perfectly. I can launch the executable, and it does what it is supposed to do.

I have a gui program that I launch from pycharm, and this gui program uses the generated executable with a subprocess.popen() call. Interestingly enough, in this case, the above issue reappears.

The only difference is that the Pycharm configuration uses a virtual env as for Python interpreter. Which is very much ok to me, but I fail to see how it can possibly impact the execution of a console executable launched from subprocess.popen().

**Comment by kayhayen** [comment]
I would really need this to be boiled down to something I can reproduce.

**Comment by kayhayen** [comment]
Lack of feedback
