### ISSUE TITLE
"Invalid script entry point" on Nuitka 0.5.29 installation

### ISSUE THREAD

**Issue by frol** [kayhayen/Nuitka#67]
The latest Nuitka 0.5.29 cannot be installed from pip:

```
$ pip install nuitka
Collecting nuitka
  Downloading Nuitka-0.5.29.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 660kB/s
Building wheels for collected packages: nuitka
  Running setup.py bdist_wheel for nuitka ... done
  Stored in directory: /home/frol/.cache/pip/wheels/46/56/4d/65ba15f23b85dbbb1fa09b2dd6c704b403cc641ec313812b53
Successfully built nuitka
Installing collected packages: nuitka
Invalid script entry point: <ExportEntry nuitka3 = nuitka.__main__:None []> for req: nuitka - A callable suffix is required. Cf https://packaging.python.org/en/latest/distributing.html#console-scripts for more information.
```

The error is the same for Python 2 and Python 3 environments (only `nuitka3` gets `nuitka` in Python 2 environment).

* Linux, Windows, Mac OS are all affected
* Python 2.7.14 and 3.6.4
* pip 9.0.1 and 9.0.3

I am one of the maintainers of Nuitka package for Conda-Forge (Anaconda) and it fails on the CI: https://github.com/conda-forge/nuitka-feedstock/pull/12 (follow the CI links at the bottom of the page)

**Comment by kayhayen** [comment]
My suspect is that the recent Python releases contain this as an issue. I am preparing a hotfix for later today, 0.5.29.1 anyway, and will add the "main" to "__main__" so it can be referenced in the "setup.py".

Yours,
Kay

**Comment by frol** [comment]
I can reproduce the issue on Ubuntu 16.04 (LTS) in a Docker container:

```
$ docker run -it --rm ubuntu bash
# apt update
...
# apt install python-pip
...
# pip install nuitka
Collecting nuitka
  Downloading Nuitka-0.5.29.tar.gz (2.0MB)
    100% |################################| 2.0MB 628kB/s
Building wheels for collected packages: nuitka
  Running setup.py bdist_wheel for nuitka ... done
  Stored in directory: /root/.cache/pip/wheels/46/56/4d/65ba15f23b85dbbb1fa09b2dd6c704b403cc641ec313812b53
Successfully built nuitka
Installing collected packages: nuitka
Invalid script entry point: <ExportEntry nuitka-run = nuitka.__main__:None []> for req: nuitka - A callable suffix is required. Cf https://packaging.python.org/en/latest/distributing.html#console-scripts for more information.
You are using pip version 8.1.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Interestingly, the issue doesn't show up on Alpine Linux.

**Comment by frol** [comment]
By the way, Nuitka 0.5.28 installs just fine in the same environment.

**Comment by kayhayen** [comment]
I pushed the fix to factory branch of git already, however this is very annoying, as I definitely have tests for the packages, that ought to see this as well:

The Debian package build for Xenial said this:

> I: pybuild base:184: /usr/bin/python3 setup.py install --root /build/nuitka-0.5.29+ds/debian/nuitka

And then just did it. Yes, it's not building a wheel, but that didn't see to be the issue. Clearly something triggers more or less checks there. It seems only pip does those. As a consequence, I should add a test for pip, probably with no upload/download, just the thing that would be pushed, if it is installable and passes basic tests.

But first, lets see this fixed, as PyPI is obviously very important source for Nuitka.

**Comment by frol** [comment]
Installation of Nuitka (0.5.29 tag and both develop and factory branches) from github doesn't trigger the error. However, if I use the archive uploaded to the PyPi (https://files.pythonhosted.org/packages/07/bc/3096dca24a07f81c428d3214601cc22e4147224d52ab5aebdf565656a1d5/Nuitka-0.5.29.tar.gz) it fails! This is super odd to me.

This completes just fine:

```
$ pip install https://github.com/kayhayen/Nuitka/archive/0.5.29.zip
```

This fails:

```
$ pip install https://files.pythonhosted.org/packages/07/bc/3096dca24a07f81c428d3214601cc22e4147224d52ab5aebdf565656a1d5/Nuitka-0.5.29.tar.gz
```

**Comment by kayhayen** [comment]
So, 0.5.29.1 is on PyPI and should work better for everybody.

**Comment by frol** [comment]
I confirm that it works on my laptop now. I will let you know once Conda-Forge CI succeeds.

**Comment by frol** [comment]
Conda-Forge CI passed: https://github.com/conda-forge/nuitka-feedstock/pull/13
