### ISSUE TITLE
CONTRIBUTING.md references non-existent pull-request template

### ISSUE THREAD

**Issue by hollasch** [kayhayen/Nuitka#70]
Intro section, second bullet point, references `.github/PULL_REQUEST_TEMPLATE.md`, which does not exist.

**Comment by kayhayen** [comment]
Thanks for reporting this. There was this plan.

Just pushed something for factory branch. Have a look at it if you would like to.

Since the link points to master, I will consider making this into the next hotfix, which will add it.

**Comment by kayhayen** [comment]
Released as 0.5.29.4
