### ISSUE TITLE
Nuitka code with other c++ Code

### ISSUE THREAD

**Issue by swatinair123** [kayhayen/Nuitka#78]
Hi ,

I had generated the c++ code from python code using nuitka -m --recurse-all code.py .
Can i use this C++ code with othet c++ codes

**Comment by kayhayen** [comment]
Thank you for the question. This is a frequent one and should be in the tracker too.

The code generated by Nuitka is not intended for use for anything but creating programs or modules or packages of Python. You can embed a Python interpreter in your C++ main application and into this you can load those compiled packages or modules.

As an aside, the generated code is C code and will not generally have any stable relationship with how the Python code looked like. Think of it as machine code.

Never is going to be supported to directly execute Nuitka generated code from other code. You will need a CPython run time.
