### ISSUE TITLE
Parsing commandline arguments using Nuitka

### ISSUE THREAD

**Issue by swatinair123** [kayhayen/Nuitka#79]
Hi ,

How can we parse commandline arguements using Nuitka. 
I had tried the code >python -m nuitka --recurse-all prog.py 10 60 -150 0 0.1 -1.0
But it is giving me an error 

Usage: __main__.py [--module] [--execute] [options] main_module.py

__main__.py: error: no such option: -1

**Comment by kayhayen** [comment]
In this case you need to add "--run", which will pass options when execution. The first non-option argument is treated as the program, and everything after it, is passed for immediate execution.
