### ISSUE TITLE
Creating a Visual studio C++ project using Nuitka

### ISSUE THREAD

**Issue by swatinair123** [kayhayen/Nuitka#80]
Hi ,

How can I create a C++project using from Nuitka. I am able to generate C++ code .But there is no .sln file to open in Visual studio. Can you pls help me 
Currently i have tried 
python -m nuitka --recurse-all program.py
and 
>python -m nuitka --recurse-all --portable program.py

But nothing is working .Please advise

**Comment by kayhayen** [comment]
You have not given a definition of what you would consider to be "working" or what is not working.

However, Nuitka is **not** a Python to C++ converter. The generated code is not for re-use, or expansion, or linking to anything else, except via embedding a Python interpreter in your program and loading compiled Python packages there.

Nuitka will on Windows use installed MSVC to compile C code to a binary. It can also use MinGW. But it does not use any of its make tools, but Scons to build.
