### ISSUE TITLE
Nuitka libs to be added corresponding to the header files

### ISSUE THREAD

**Issue by swatinair123** [kayhayen/Nuitka#83]
Hi ,
I am compiling a python code using Nuitka. I have got the .cpp files .Now i have opened a new project in Visual studio and added all the .cpp files.But i am not able to find the .lib files corresponding to the header files in  Nuitka-0.5.29.4\nuitka\build\include  necessary for it because of it i am getting the unresolved symbol errors .
Is there any makefile which does the linking in the folder. Please provide us for some inputs in this regards

**Comment by brupelo** [comment]
@swatinair123 I strongly recommend you take a look first to the [docs](http://nuitka.net/doc/user-manual.html). I'm not sure what you're trying to compile by yourself all the cpp files generated by nuitka but that's not how it works.

To generate an executable out of your python code, all you need to do is opening a visual command prompt where the visual studio compiler will be available and running nuitka there, easy peasy.

NS: In the docs @kayhayen recommends `Visual Studio 2017 or higher on Windows [3], older versions may work, but are not officially supported. Configure to use English language pack for best results (Nuitka filters away garbage outputs, but only for that language).` but I use Visual Studio 2015 and I haven't had any problems so far compiling the nuitka generated content.

Hope it helps.

**Comment by swatinair123** [comment]
Hi I have compiled the python file using the command python -m nuitka --recurse-all program.py from the anaconda prompt and I have got the .cpp files and its .obj files in program.build folder. ACtually i was trying to add these .cpp files and create a new project .

Now i will try ececuting the command  python -m nuitka --recurse-all program.py from the Visual command prompt. Can you please tell me if i am on track.

**Comment by brupelo** [comment]
@swatinair123 Yeah, you're definitely on the right track, now, in the visual command prompt try the next command `nuitka3 --recurse-all --standalone main.py`, the standalone option will create a main.dist folder containing your compiled program.py.

Btw, instead opening issue for just asking it'd be helpful to give feedback as well to @kayhayen about the existing docs, the fact you're asking these questions means the existing docs are lacking something for newcomers to get up and running more easily with nuitka.

The goal should be making nuitka the most popular tool between the python community so new users giving feedback to improve/contribute to the project somehow is definitely a win ;)

Good luck.

**Comment by kayhayen** [comment]
Using the .c files directly is unsupported. They contain no interfaces for you to use.

Check this out: https://docs.python.org/2/extending/embedding.html

You can embed Python, and load modules, which can be extension modules compiled with Nuitka, and that is the only thing that works.

Nuitka is not a way to glue your C/C++ code together with Python code directly. Not now, and I would say never.

Yours,
Kay

**Comment by swatinair123** [comment]
Hi , So instead of the .exe files is there a way to create .dlls using Nuitka

**Comment by kayhayen** [comment]
@swatinair123 With "--module" you will create an ".pyd" file, which is an extension module that Python can load. It is not creating DLLs at all. Technically ".pyd" are really "DLL", but nothing but the Python interpreter (potentially the one you embedded in your program) will know how to use it or provide the environment for it to be used.
