### ISSUE TITLE
Proposal about decoupling nuitka core modules from Options

### ISSUE THREAD

**Issue by brupelo** [kayhayen/Nuitka#87]
Probably you won't be interested on this one as I can understand it just works for you but after reading nuitka source code I've seen a bunch of modules across the whole project being coupled with Options, which is initialized/parsed on `__main__.py`. Let me tell you in a nice way that this is a really bad coding practice, period. By having this dependency across many of the project modules with the Options file you've made than those modules can't be unit tested in isolation easily or even used independently and that's really bad.

One example, yesterday I wanted to make some external tests using nuitka as a dependency of my project and it was a real nightmare. Let's say I wanted to use some of Nuitka code/modules, right now that's just not possible for few reasons, the most important being this ugly coupling with Options.py :)

If you're interested on this one I would be willing to refactor the code so the packages would become decoupled. I just wanted to comment this one with you first as I'm probably sure if I made a PR out of the blue refactoring a lot of your code you wouldn't be happy with it and it'd be rejected straightaway, and it'd be a waste of time :) . Many coders tend to dislike other people suggestions when it comes to refactoring their projects with things that works for them, one example of one PR I'd made out of the blue few months [ago](https://github.com/cb109/sublime3dsmax/pull/20) and it got rejected, at that time I've learned the lesson providing PRs out the blue is not a good idea usually.

Let me put it differently, as I've mentioned in another threads the current CLI has a lot of options who are just probably interesting for you (coder) and not casual users and that's fine, your project your rules... But... wouldn't be great if another tools using nuitka core was also possible? An example, yesterday I wanted to make a fast test that worked only with a little subset of the current official spectrum, instead covering {python("2.6", "2.7", "3.3", "3.4", "3.5", "3.6"), all major operating systems, a lot of CLI options} I just wanted to a test working on {python3.6, windows, standalone_mode}, and that proved to be a nightmare... at one point, I've even tried to monkey patching some modules at runtime, which was a really bad idea so I've stopped there.

Btw, the test was going to be a little tool like:

    usage = "usage: %prog module1 module2 ... moduleN"

No options at all, it would work just in standalone mode, that way I'd could create a stress test of many simple scripts and tests the new faster windows cache (got a 1st buggy version +/- working)

So... please let me know your thoughts about this proposal.

Yours,
Bruno

**Comment by brupelo** [comment]
Gathered a list of modules coupled with Options:

    codegen
    -------
    AttributeCodes.py
    CodeObjectCodes.py
    ConditionalCodes.py
    ConstantCodes.py
    Contexts.py
    DictCodes.py
    ErrorCodes.py
    EvalCodes.py
    GeneratorCodes.py
    SliceCodes.py
    SubscriptCodes.py
    TryCodes.py
    YieldCodes.py

    finalizations
    -------------
    FinalizeMarkups.py

    freezer
    -------
    BytecodeModuleFreezer.py
    Standalone.py

    importing
    ---------
    Importing.py
    Recursion.py

    root
    ----
    MainControl.py

    nodes
    -----
    FunctionNodes.py
    ModuleAttributeNodes.py
    ModuleNodes.py
    NodeBases.py

    optimizations
    -------------
    Graphs.py
    Optimization.py

    plugins
    -------
    PluginBase.py
    Plugins.py

    plugins\standard
    ----------------
    DataFileCollectorPlugin.py
    MultiprocessingPlugin.py
    PmwPlugin.py
    PySidePyQtPlugin.py

    tree
    ----
    Building.py
    ReformulationNamespacePackages.py
    ReformulationWithStatements.py
    SourceReading.py
    TreeHelpers.py

    tests
    -----
    test_warnings.py
    test_cmd_line.py
    test_cmd_line.py
    test_warnings\__init__.py

These are the ones than should be refactored.

**Comment by kayhayen** [comment]
Don't be shy to tell me what's bad, esp. when it's bad.

So, essentially the way I see it, Nuitka needs to know some decisions, and a place to look it up. Lets go with standalone mode or not. If that is called options, modes, doesn't matter much.

Places will still import something, and access that via some name or key, or function, right? Or do you want to pass an object along for them to use in functions? 

The thing you are complaining about, and rightfully so, is that the way these values are to be populated, Nuitka is giving you are hard time to be doing that in code. I am totally OK for there to be a module, where values and their defaults live, and alternative ways to fill them in, then run Nuitka without the command line being even considered by Nuitka.

I really like code driven configuration. When e.g. considering which packages to include, code will often be more usable than command line. I am a fan of Buildbot and Nikola, where config is code, in a "master.py" or "conf.py", but Nuitka isn't like that.

Actually I wouldn't know how to properly do it properly. Can you sketch a minimal example of how this works in practice?

**Comment by brupelo** [comment]
> Don't be shy to tell me what's bad, esp. when it's bad.

That is a really nice attitude of yours, like it!

> Actually I wouldn't know how to properly do it properly. Can you sketch a minimal example of how this works in practice?

Sure thing, I'll be writing a little bit about some options of refactoring this type of code after I finish some other stuff first ;)

**Comment by brupelo** [comment]
In order to refactor properly this one let's start by considering all cases of module decoupling from Options.py one by one. 

### Case0

Structure: This 15min example shows the case where the options used in a function can be considered as optional parameters of the function itself.
Solution: Remove the import and extend the function with optional params (or object, or default params, ...). 
Example: [case0](https://github.com/brupelo/nuitka_tests/tree/master/refactoring_examples/case0).

**Comment by kayhayen** [comment]
From your example, for code generation, its options probably should be part of "context". That is already passed along to everything, and changes.

Imagine e.g. that only some modules are to be compiled with full compatibility (which means no incompatible improvements over CPython like better errors, no misleading stuff, being sensible within Python spec) on, currently not even possible. Options related to code generation should be accessed from there.

For the node tree, I don't think any such context can exist. Passing **kwargs all the way around is pretty horrible, as it contains no error checking. There I think "config" module makes sense indeed, and could be a way to go. I wonder if you have more alternatives though.

**Comment by brupelo** [comment]
Very brief note to clarify a little bit more about case0. 

Case0 isn't suggesting you should be forced to move out the Options to the function definition like {**kwargs, default parameters, object parameters} each time you find a function using Options in the body. Just do so if it makes sense and the final refactored function will be **correct**, before putting an example I'd like quoting a really nice sentence from the book "Clean Code: A Handbook of Agile Software Craftsmanship".

> The ideal numbers of arguments for a function is zero (niladic). Next comes one (monadic), followed closely by two (dyadic). Three arguments (triadic) should be avoided where possible. More than three (polyadic) requires very special justification ‐ and then shouldn't be used anyway.

Let's imagine a trivial function from `Standalone.py`, `removeSharedLibraryRPATH(filename)` which is using `Options.isShowInclusion()` in the body, if we consider this one corresponds to case0 we could refactor it to look like one of below options:

    removeSharedLibraryRPATH(filename, is_show_inclusion=False)

    removeSharedLibraryRPATH(filename, **kwargs)

    removeSharedLibraryRPATH(filename, options=None)

Right? Please don't! :) . That'd be just incorrect and the function interface would be broken... not broken but from a pragmatic point of view the interface would become wrong. Why? Well, in that case the original interface `removeSharedLibraryRPATH(filename)` was already correct and what it was wrong in that case was the fact than that particular function was using an option than needs to be parsed/evaluated at runtime, that's not good and THAT is what should be refactored somehow in that case. 

How to refactor it? One possible choice would be applying the solution of case1 or maybe getting rid of that code as it doesn't add any real value at all. Although I think this function doesn't correspond  neither to case0 nor case1.

If you think about it, by getting rid of code you'll decouple the function from Options almost "for free". I do really like getting rid of debugging code in my personal projects very often, not scared of it at all tbh. Once I've checked correctness of the code I'll clean it up, I like to stick to the rule of "less code, less maintenance".

At the end of the day, the best person that can evaluate whether a particular piece of debugging code will be worth keeping is the author. He'll know better to answer whether a particular debugging code is going to save time in the future improving the project. Btw, when it comes to debugging&logging usually is a good idea to have a single point of failure, that is, modifying just the logger object used by a particular module/functions instead having blocks like `if option.whatever_debug_option: ` inside the function bodies.

Anyway, I stop here, this one was just to clarify a little bit more about case0 as I've read you said 

> Passing **kwargs all the way around is pretty horrible, as it contains no error checking

as that comment makes sense... said otherwise, just use **kwargs when it's correct to do so.

Btw, the idea of bringing up all existing cases so when it comes to refactoring it won't take you too much time doing the refactoring and it'll be possible to make in a very automatized mechanical way. When coding by myself I don't like to think much about when applying this or that pattern/rule. I like when I can refactor the stuff as fast as possible in a very mechanical way (like a robot :)) . For instance, when you simplify math equations you don't think too much about whether you should use this or that rule, you just simplify the equation in a very mechanical way using the right patterns at each time, same should apply when simplifying code ;) .

Think about it, the fact you can't agree with colleagues on how to refactor a particular piece of code that is just wrong tends to be a waste of time for the company. Refactoring rules shouldn't leave room to discussion and should be as clear as water.

Tsk, at the end it wasn't a fast note, sorry about that... I do really love talking/discussing about software engineering topics, architectures, refactoring and so on... :)

**Comment by brupelo** [comment]
@kayhayen Kay, how you doing? I hope you're fine... Haven't had too much time the last months to play around with one of my favourite projects but today I've found some time and spent few hours playing around with this old one.

Take a look to this [one](https://github.com/brupelo/Nuitka/commit/039eada7f79db5fb66bd4c88f32f6453bacd5922), before coming up with that piece of code I've already tried a fair ammount of alternatives... I didn't really like none of them... I'd say this one is the less intrusive one I've been able to think of.

Of course it's not the type of elegant solution I'd like to implement (not my favourite one)... But the other ones I wanted to implement would require more intrussive code and removing/rewriting a fair ammount of producting code. In my experience, these type of major rewritings lead to introduce more bugs and slow down the overall progress, so thanks but no :)

The proposed one keeps the current functionality AND allows to inject custom options and use a custom parser. Next thing I'd like to try is giving the ability to inject a custom `MainControl` without relying in the current one but let's hear first your thoughts about this one... or maybe you already got some better plans in mind.

Anyway, as I've commented few months ago, the big idea would be splitting nuitka into a backend that can be used to write 1 or more frontends. Why? That way you'll allow devs coding ups their custom frontends, which means... 
  
  a) Devs will get engaged to test nuitka more easily
  b) Which means more ideas coming from people
  c) More flexibility 
  d) You'll be able to write lightweights frontends that are more user-friendly easily
  e) Frontends to be used by devs and frontends to be used by casual users (related to d)

For instance, right now I wanted to write a simple frontend that allows me to skip certain stages when creating an exe (i just want to compile once) so I can invest all my efforts on improving the freezing stage, in order to do so I'll just need few CLI options and not the whole bunch of existing ones. Workflow example:
 
   1) my_custom_frontend main.py --standalone  (~100s)
   2) my_custom_frontend main.py --standalone --skip-compilation (~1s)
   3) fix code
   4) my_custom_frontend main.py --standalone --skip-compilation (~1s)
   5) fix code
   6) my_custom_frontend main.py --standalone --skip-compilation (~1s)   
   ...

Instead the more expensive:

   1) my_custom_frontend main.py --standalone  (~100s)
   2) fix code
   3) my_custom_frontend main.py --standalone  (~30s)
   4) fix code
   5) my_custom_frontend main.py --standalone  (~30s)
   ... and so on

You can see the 1st workflow is 100s+N*1s  vs 2nd workflow 100s+N*30s :) . Right now compilation is crazy expensive in the general case (not hello world scripts).

Btw, one of the reasons I've come back today to play around with nuitka is because after converting this little [tool](https://blog.didierstevens.com/programs/disitool/) into an exe (in my dev box) and copy it into a fresh windows7 virtual machine the exe wouldn't run because some missing dlls.

Ooops, already wrote too much text, I'm off ;D

Yours,
B

**Comment by brupelo** [comment]
In addition, here's a simple example of usage of the above proposal:

    from nuitka import __main__
    import sys


    class DefaultOptions:

        def __init__(self):
            self.__dict__ = {
                "allow_reexecute": True,
                "assume_yes_for_downloads": False,
                "clang": False,
                "debug": False,
                "debugger": False,
                "detect_missing_plugins": True,
                "disabled": False,
                "display_tree": False,
                "dump_xml": False,
                "executable": True,
                "experimental": [],
                "explain_imports": False,
                "file_reference_mode": None,
                "generate_c_only": False,
                "graph": False,
                "icon_path": None,
                "immediate_execution": False,
                "improved": True,
                "include_modules": [],
                "include_packages": [],
                "is_standalone": True,
                "jobs": 8,
                "keep_pythonpath": False,
                "list_plugins": False,
                "lto": False,
                "mingw": False,
                "msvc": None,
                "no_dependency_cache": False,
                "obsolete_executable": False,
                "output_dir": "",
                "plugins_disabled": [],
                "plugins_enabled": [],
                "profile": False,
                "pyi_file": True,
                "python_arch": None,
                "python_debug": None,
                "python_flags": [],
                "python_scons": None,
                "python_version": None,
                "recompile_c_only": False,
                "recurse_all": True,
                "recurse_extra": [],
                "recurse_extra_files": [],
                "recurse_modules": [],
                "recurse_none": False,
                "recurse_not_modules": [],
                "recurse_stdlib": False,
                "remove_build": False,
                "show_inclusion": False,
                "show_memory": False,
                "show_progress": True,
                "show_scons": False,
                "statement_lines": True,
                "trace_execution": False,
                "unstripped": False,
                "update_dependency_cache": False,
                "verbose": True,
                "warn_implicit_exceptions": False,
                "warn_unusual_code": False,
                "win_disable_console": False
            }


    def help():
        print('usage: py2c main_module')
        sys.exit()

    def main():
        class Config():
            def __init__(self):
                self.options = DefaultOptions()
                self.positional_args = sys.argv[1:]
                self.extra_args = []
                self.is_nuitka_run = False

        c = Config()

        if not c.positional_args:
            help()

        if not c.options.immediate_execution and len(c.positional_args) > 1:
            help()

        __main__.main(c)


    if __name__ == "__main__":
        main()

**Comment by brupelo** [comment]
TODO (note to myself): Check how to fix import errors if trying to use __main__ outside nuitka 

    import sys


    class DefaultOptions:

        def __init__(self):
            self.__dict__ = {
                "allow_reexecute": True,
                "assume_yes_for_downloads": False,
                "clang": False,
                "debug": False,
                "debugger": False,
                "detect_missing_plugins": True,
                "disabled": False,
                "display_tree": False,
                "dump_xml": False,
                "executable": True,
                "experimental": [],
                "explain_imports": False,
                "file_reference_mode": None,
                "generate_c_only": False,
                "graph": False,
                "icon_path": None,
                "immediate_execution": False,
                "improved": True,
                "include_modules": [],
                "include_packages": [],
                "is_standalone": True,
                "jobs": 8,
                "keep_pythonpath": False,
                "list_plugins": False,
                "lto": False,
                "mingw": False,
                "msvc": None,
                "no_dependency_cache": False,
                "obsolete_executable": False,
                "output_dir": "",
                "plugins_disabled": [],
                "plugins_enabled": [],
                "profile": False,
                "pyi_file": True,
                "python_arch": None,
                "python_debug": None,
                "python_flags": [],
                "python_scons": None,
                "python_version": None,
                "recompile_c_only": False,
                "recurse_all": True,
                "recurse_extra": [],
                "recurse_extra_files": [],
                "recurse_modules": [],
                "recurse_none": False,
                "recurse_not_modules": [],
                "recurse_stdlib": False,
                "remove_build": False,
                "show_inclusion": False,
                "show_memory": False,
                "show_progress": True,
                "show_scons": False,
                "statement_lines": True,
                "trace_execution": False,
                "unstripped": False,
                "update_dependency_cache": False,
                "verbose": False,
                "warn_implicit_exceptions": False,
                "warn_unusual_code": False,
                "win_disable_console": False,
                "skip_compilation": False
            }


    def help():
        print('usage: py2c main_module')
        sys.exit()


    def main():
        print("__main__.main", sys.path)

        from nuitka import __main__

        class Config():
            def __init__(self):
                self.options = DefaultOptions()
                self.positional_args = sys.argv[1:]
                self.extra_args = []
                self.is_nuitka_run = False

        c = Config()

        if not c.positional_args:
            help()

        if not c.options.immediate_execution and len(c.positional_args) > 1:
            help()

        # __main__.main()

        __main__.initialize()

        # For re-execution, we might not have done this.
        from nuitka import Options                  # isort:skip
        Options.injectConfig(c)

        __main__.configure(__name__, Options)

        # Now the real main program of Nuitka can take over.
        from nuitka import MainControl  # isort:skip
        MainControl.main()

        if Options.isShowMemory():
            from nuitka.utils import MemoryUsage
            MemoryUsage.showMemoryTrace()

    if __name__ == "__main__":
        main()

The above one (living outside nuitka) would produce nuitka import error because the reexecution using sys.flags.no_site `ie: python -S ...`

**Comment by brupelo** [comment]
At #119 you wrote:

> @brupelo I feel this content is misplaced in this issue. I enjoy discussions too, esp. if they have substance and are concrete. I would love to see and discuss based on commits achieving these goals. However, this should happen in the issues intended for it, limited to one specific issue, and if it's general on the mailing list. There I have frequently explained my stance on how I develop Nuitka.

@kayhayen I think you're actually right. As you can see, many times I tend to write long chunks of text talking about very abstract things and that's mainly because it feels good exposing ideas based on experience/knowledge. By doing so maybe some interesting discussion emerges and if we're lucky we both learn one or two new cool things, I'm all in to improve my skills as a coder with this type of conversations :)

But maybe you're right and github issues is not the best place to have this kind of long general conversations, actually from what I've seen so far from multiple issues I've opened, it seems it is not a very effective way to get things done and improving nuitka :) . So I guess you've got a point with your previous `I enjoy discussions too, esp. if they have substance and are concrete. I would love to see and discuss based on commits achieving these goals. ` comment, it seems a legit comment :D

On the other hand, I'm the type of coder who likes to dispatch large features all at once (I usually know beforehand how to tackle the whole thing at once) but that's a problem here... usually if it's my project and I'm working on it full-time and I don't have to agree with anybody about my code I'll deliver the feature in a very optimal and fast way. 

But in this case, we're talking about an open-source project where 1) People need to use their spare time, which usually it's pretty limiting (at least it is over here) and 2) it's needed to agree/discusing with others about possible commits to merge. Well, that's really time consuming but of course, it's definitely a necessary thing to do, otherwise If people delivered large big chunks of code/features at once and the main author/s didn't agree those contributors would become frustrated and not willing to contribute to the project anymore... To be blunt here, I've always thought open-source contributions/workflows are quite tricky to manage and handle, but maybe it's just me who's not very used to contribute to these type of projects :)

Anyway, coming back to this issue, I'm really interested on getting done this issue delivered as I consider it a first major step in order to sanitize a bit the whole project. But not sure how to tackle the right way, what do you think is the best way to address it? For instance, let's say ~90files need to be changed and I've got like 10/15 minutes each day to spare on this. What's the best way to progress and getting feedback from you? I was thinking about a workflow like:

 - I create a feature branch from develop and I open an unfinished PR 
 - I'll find little bit of spare time and eventually I'll be progressing on the feature, although many days I won't be able to even find not even a single minute to update the PR. I'll tweak a little bit some files and I'll push them, the PR will get updated and I'll get your feedback so we'll be able to discuss if other approaches would be better
 - On many pushes, there will be times that some stuff will be missing and the project not behaving exactly like it's behaving right now but eventually the feature will get done and we'll have decoupled completely the Options module from all subsystems
 - When the previous point is complete, I'll be able to prove with few examples than writing tools with custom CLI parsers or GUI tools has become possible

What do you think? Does it make sense what I'm saying or it's just a wasteful way to proceed here?

As you can see, I'm quite a newbie with git contributions so maybe what I'm proposing here is nonsense and not the best way to go... So please let me know how people tend to contribute with large features/refactorings/bug_fixings like this when they got pretty limited time.

Yours,
B
