### ISSUE TITLE
Conflicting .dll (icuuc.dll)

### ISSUE THREAD

**Issue by LarsK1** [kayhayen/Nuitka#96]
Hey,
every time I want to compile my script, I ran in to the following error:
`Error, conflicting DLLs for 'icuuc.dll'.
c:\windows\system32\icuuc.dll used by:
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_hashlib.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\sip.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_ssl.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\imageformats\qtga.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\imageformats\qwbmp.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\platforms\qminimal.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_msi.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\imageformats\qsvg.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_elementtree.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\imageformats\qwebp.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\iconengines\qsvgicon.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\QtCore.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_decimal.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_tkinter.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\pyexpat.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\QtGui.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\mediaservice\qtmedia_audioengine.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\select.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\imageformats\qico.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_sqlite3.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_overlapped.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_socket.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\imageformats\qtiff.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\QtWidgets.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\imageformats\qjpeg.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_ctypes.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_lzma.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\printsupport\windowsprintersupport.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\mediaservice\wmfengine.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\mediaservice\dsengine.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\platforms\qwindows.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\imageformats\qicns.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_multiprocessing.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\platforms\qwebgl.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_asyncio.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\imageformats\qgif.dll
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\_bz2.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\unicodedata.pyd
   E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\PyQt5\qt-plugins\platforms\qoffscreen.dll
different from
e:\programme\python\kanzlei\mail\kompilat\updater.dist\icuuc.dll used by    E:\Programme\Python\Kanzlei\Mail\Kompilat\Updater.dist\Updater.exe`
The crazy thing about it is, that the dll in the application is wrong?!

**Codeexample:**
`from PyQt5 import QtWidgets, QtCore`

_Information:
Nuitka-Version: 0.5.33rc4
Python-Version: 3.6.6 (x64)
Platform: Win 10 (Build 17733)
Nuitka-Install: Easy-Install_

**Comment by kayhayen** [comment]
This DLL appears to be a system one, according to https://procpedia.com/file/5771/What-is-icuuc-dll-and-How-To-Fix-It/

I am going to add it to the list of system DLLs that need not be included, then the issue will go away.

I pushed a fix to the factory branch, you can try it out like this:
http://nuitka.net/doc/factory.html

Let me know if it helps or if e.g. other DLL is now complained about.

Yours,
Kay

**Comment by LarsK1** [comment]
Now, it's missing again:
`Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\nuitka\__main__.py", line 218, in <module>
    main()
  File "C:\Program Files\Python36\lib\site-packages\nuitka\__main__.py", line 212, in main
    MainControl.main()
  File "C:\Program Files\Python36\lib\site-packages\nuitka\MainControl.py", line 851, in main
    standalone_entry_points = standalone_entry_points
  File "C:\Program Files\Python36\lib\site-packages\nuitka\freezer\Standalone.py", line 1151, in copyUsedDLLs
    if filecmp.cmp(dll_filename1, dll_filename2):
  File "C:\Program Files\Python36\lib\filecmp.py", line 52, in cmp
    s2 = _sig(os.stat(f2))
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'e:\\programme\\python\\kanzlei\\mail\\kompilat\\updater.dist\\icuuc.dll'`

**Comment by kayhayen** [comment]
Please run this with --force-dll-dependency-cache-update once. Nuitka remembers the bad detection previously made, or so I think. Should be good then.

**Comment by LarsK1** [comment]
@kayhayen 
Yes, I will try so.  

_So I will see the results in about 2 hours, because the dependency look-up is needing so long? What is differnt at your workspace?_

**Comment by kayhayen** [comment]
There is way too many PyQt plugins and DLLs, kind of worst case. And that is before you start using other stuff, which may also have extension modules.

**Comment by LarsK1** [comment]
@kayhayen 
It's working now!

Thank's so much!

**Comment by LarsK1** [comment]
There's another error, the both dlls (iccuin.dll, icuuc.dll) won't be deleted at the start.
```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\nuitka\__main__.py", line 218, in <module>
    main()
  File "C:\Program Files\Python36\lib\site-packages\nuitka\__main__.py", line 212, in main
    MainControl.main()
  File "C:\Program Files\Python36\lib\site-packages\nuitka\MainControl.py", line 851, in main
    standalone_entry_points = standalone_entry_points
  File "C:\Program Files\Python36\lib\site-packages\nuitka\freezer\Standalone.py", line 1183, in copyUsedDLLs
    target_path
  File "C:\Program Files\Python36\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Python36\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'E:\\Programme\\Python\\Kanzlei\\Mail\\Kompilat\\Mail.dist\\icuuc.dll'
```
So we have to add a check, if file's are elready existing.  See #97

**Comment by kayhayen** [comment]
That permission error very likely comes from the program using it still running.

```
    # Prepare the ".dist" directory, throwing away what was there before.
    if Options.isStandaloneMode():
        standalone_dir = getStandaloneDirectoryPath(main_module)
        removeDirectory(
            path          = standalone_dir,
            ignore_errors = True
        )
        makePath(standalone_dir)

```

This could not ignore errors, then it would simply crash when that happens. Unfortunately locks in Windows often persist for a while after a program closes, e.g. Virus checkers, etc. seem to do this, leading to spurious errors.

However, this ignoring of errors is pretty old, basically from the inception of the code, so it may not be that necessary, because usually a lot of time will have passed since the execution, likely. It would be nice to catch that permission error and make it into a nicer error message that explains it. Esp. because the .dist folder will survive, but will contain useless stuff only.

Do you want to update your PR to do that instead?

As for checking if something already exists, well yes, but changed content shouldn't survive, so before accepting it, a comparison of the two files would be necessary. But I think we should be sure nothing exists in the dist folder. From the git log I got the idea that it's rather important for that to be the case or else resolving dependencies is bound to make mistakes.

Yours,
Kay

**Comment by kayhayen** [comment]
I pushed to factory the change that will use "shutil.copyfile" over "shutil.copy". I am going to include that in the next hotfix as well.

**Comment by kayhayen** [comment]
Release as part of 0.5.32.7
